const hscVocabDB = [
    // Nelson Mandela & Human Rights
    { word: "Discrimination", type: "Noun", meaning: "বৈষম্য", syn: "Injustice, Bias, Bigotry" },
    { word: "Emancipation", type: "Noun", meaning: "মুক্তি", syn: "Freedom, Liberation" },
    { word: "Reconciliation", type: "Noun", meaning: "মীমাংসা", syn: "Settlement, Reunion" },
    { word: "Negotiation", type: "Noun", meaning: "আলোচনা", syn: "Discussion, Compromise" },
    { word: "Manifestation", type: "Noun", meaning: "প্রকাশ", syn: "Display, Expression" },
    { word: "Apartheid", type: "Noun", meaning: "বর্ণবাদ", syn: "Segregation, Racism" },
    { word: "Resolve", type: "Noun/Verb", meaning: "সংকল্প / সমাধান", syn: "Determination, Settle" },
    { word: "Oppression", type: "Noun", meaning: "নিপীড়ন", syn: "Persecution, Abuse" },
    { word: "Dignity", type: "Noun", meaning: "মর্যাদা", syn: "Honor, Respect" },
    { word: "Mythic", type: "Adj", meaning: "পৌরাণিক", syn: "Legendary, Fictional" },
    
    // Kuakata & Environment
    { word: "Pristine", type: "Adj", meaning: "আদিম / অকৃত্রিম", syn: "Pure, Unspoiled" },
    { word: "Indigenous", type: "Adj", meaning: "স্বদেশী / স্থানীয়", syn: "Native, Local" },
    { word: "Picturesque", type: "Adj", meaning: "ছবির মতো সুন্দর", syn: "Scenic, Beautiful" },
    { word: "Sanctuary", type: "Noun", meaning: "আশ্রয়স্থল", syn: "Refuge, Haven" },
    { word: "Migratory", type: "Adj", meaning: "পরিযায়ী", syn: "Traveling, Roving" },
    { word: "Expanse", type: "Noun", meaning: "বিস্তৃতি", syn: "Vastness, Area" },
    { word: "Destructive", type: "Adj", meaning: "ধ্বংসাত্মক", syn: "Devastating, Ruinous" },
    { word: "Erosion", type: "Noun", meaning: "ক্ষয়", syn: "Deterioration, Wearing away" },
    { word: "Magnificent", type: "Adj", meaning: "চমৎকার", syn: "Splendid, Glorious" },
    { word: "Devastation", type: "Noun", meaning: "ধ্বংস", syn: "Destruction, Ruin" },

    // Diaspora & Culture
    { word: "Diaspora", type: "Noun", meaning: "দেশান্তর", syn: "Migration, Displacement" },
    { word: "Assimilation", type: "Noun", meaning: "একত্রীকরণ", syn: "Integration, Merging" },
    { word: "Heritage", type: "Noun", meaning: "ঐতিহ্য", syn: "Tradition, Ancestry" },
    { word: "Settlement", type: "Noun", meaning: "বসতি", syn: "Colony, Community" },
    { word: "Phenomenon", type: "Noun", meaning: "ঘটনা", syn: "Occurrence, Event" },
    { word: "Catastrophic", type: "Adj", meaning: "বিপর্যয়কর", syn: "Disastrous, Fatal" },
    { word: "Ancestors", type: "Noun", meaning: "পূর্বপুরুষ", syn: "Forefathers, Predecessors" },
    { word: "Noteworthy", type: "Adj", meaning: "উল্লেখযোগ্য", syn: "Remarkable, Important" },
    { word: "Alienation", type: "Noun", meaning: "বিচ্ছিন্নতা", syn: "Isolation, Detachment" },
    { word: "Fascination", type: "Noun", meaning: "মুগ্ধতা", syn: "Attraction, Captivation" },

    // Adolescence & Health
    { word: "Adolescence", type: "Noun", meaning: "কৈশোর", syn: "Youth, Teen years" },
    { word: "Transition", type: "Noun", meaning: "পরিবর্তন / রূপান্তর", syn: "Change, Shift" },
    { word: "Vulnerability", type: "Noun", meaning: "দুর্বলতা", syn: "Weakness, Risk" },
    { word: "Puberty", type: "Noun", meaning: "বয়ঃসন্ধিকাল", syn: "Maturation" },
    { word: "Potential", type: "Noun/Adj", meaning: "সম্ভাবনা", syn: "Capability, Possible" },
    { word: "Mortality", type: "Noun", meaning: "মৃত্যুর হার", syn: "Fatality, Death rate" },
    { word: "Complication", type: "Noun", meaning: "জটিলতা", syn: "Difficulty, Problem" },
    { word: "Malnutrition", type: "Noun", meaning: "অপুষ্টি", syn: "Starvation, Undernourishment" },
    { word: "Empowerment", type: "Noun", meaning: "ক্ষমতায়ন", syn: "Authorization, Enablement" },
    { word: "Initiative", type: "Noun", meaning: "উদ্যোগ", syn: "Action, Plan" },

    // Linking Words (Crucial for Rearrange & Cloze)
    { word: "Consequently", type: "Adverb", meaning: "ফলস্বরূপ", syn: "Therefore, As a result" },
    { word: "Furthermore", type: "Adverb", meaning: "অধিকন্তু", syn: "Moreover, In addition" },
    { word: "Nevertheless", type: "Adverb", meaning: "তা সত্ত্বেও", syn: "However, Still" },
    { word: "Subsequently", type: "Adverb", meaning: "পরবর্তীতে", syn: "Afterwards, Later" },
    { word: "Simultaneously", type: "Adverb", meaning: "একই সাথে", syn: "Concurrently, At the same time" },
    { word: "Inevitably", type: "Adverb", meaning: "অনিবার্যভাবে", syn: "Unavoidably, Certain" },
    { word: "Particularly", type: "Adverb", meaning: "বিশেষভাবে", syn: "Specifically, Especially" },
    { word: "Significantly", type: "Adverb", meaning: "তাৎপর্যপূর্ণভাবে", syn: "Importantly, Notably" },
    { word: "Conversely", type: "Adverb", meaning: "বিপরীতভাবে", syn: "Oppositely, On the other hand" },
    { word: "Accordingly", type: "Adverb", meaning: "তদনুসারে", syn: "Correspondingly, Properly" }, 
    // Traffic & Road Safety
    { word: "Congestion", type: "Noun", meaning: "যানজট / ভিড়", syn: "Overcrowding, Blockage" },
    { word: "Tragic", type: "Adj", meaning: "মর্মান্তিক", syn: "Disastrous, Heartbreaking" },
    { word: "Reckless", type: "Adj", meaning: "বেপরোয়া", syn: "Careless, Irresponsible" },
    { word: "Pedestrian", type: "Noun", meaning: "পথচারী", syn: "Walker, Passerby" },
    { word: "Intersection", type: "Noun", meaning: "চৌরাস্তা / মোড়", syn: "Crossroad, Junction" },
    { word: "Commuter", type: "Noun", meaning: "নিয়মিত যাতায়াতকারী", syn: "Traveler, Passenger" },
    { word: "Enforce", type: "Verb", meaning: "কার্যকর করা", syn: "Impose, Implement" },
    { word: "Hazard", type: "Noun", meaning: "বিপদ", syn: "Danger, Risk" },
    { word: "Violation", type: "Noun", meaning: "লঙ্ঘন", syn: "Breach, Disobedience" },
    { word: "Awareness", type: "Noun", meaning: "সচেতনতা", syn: "Consciousness, Knowledge" },

    // Dreams & Literature
    { word: "Illusion", type: "Noun", meaning: "ভ্রম / মোহ", syn: "Fantasy, Delusion" },
    { word: "Visionary", type: "Adj", meaning: "দূরদর্শী", syn: "Imaginative, Idealistic" },
    { word: "Nightmare", type: "Noun", meaning: "দুঃস্বপ্ন", syn: "Bad dream, Terror" },
    { word: "Ambition", type: "Noun", meaning: "উচ্চাকাঙ্ক্ষা", syn: "Aspiration, Goal" },
    { word: "Subconscious", type: "Adj", meaning: "অবচেতন", syn: "Hidden, Inner" },
    { word: "Fascinating", type: "Adj", meaning: "চিত্তাকর্ষক", syn: "Captivating, Engaging" },
    { word: "Frustration", type: "Noun", meaning: "হতাশা", syn: "Disappointment, Defeat" },
    { word: "Endeavor", type: "Noun/Verb", meaning: "প্রচেষ্টা", syn: "Attempt, Effort" },
    { word: "Perseverance", type: "Noun", meaning: "অধ্যবসায়", syn: "Persistence, Dedication" },
    { word: "Triumph", type: "Noun", meaning: "বিজয়", syn: "Victory, Success" },

    // Food Adulteration & Health
    { word: "Adulteration", type: "Noun", meaning: "ভেজাল", syn: "Contamination, Pollution" },
    { word: "Toxic", type: "Adj", meaning: "বিষাক্ত", syn: "Poisonous, Deadly" },
    { word: "Pesticide", type: "Noun", meaning: "কীটনাশক", syn: "Insecticide, Chemical" },
    { word: "Preservative", type: "Noun", meaning: "সংরক্ষণকারী উপাদান", syn: "Additive, Chemical" },
    { word: "Consumption", type: "Noun", meaning: "গ্রহণ / ব্যবহার", syn: "Eating, Usage" },
    { word: "Syndrome", type: "Noun", meaning: "লক্ষণসমষ্টি", syn: "Disease, Disorder" },
    { word: "Culprit", type: "Noun", meaning: "অপরাধী", syn: "Offender, Criminal" },
    { word: "Greed", type: "Noun", meaning: "লোভ", syn: "Desire, Selfishness" },
    { word: "Remedy", type: "Noun", meaning: "প্রতিকার", syn: "Cure, Treatment" },
    { word: "Vigilance", type: "Noun", meaning: "সতর্কতা", syn: "Watchfulness, Alertness" },

    // Environment & Climate Change
    { word: "Greenhouse", type: "Noun", meaning: "গ্রিনহাউস", syn: "Glasshouse" },
    { word: "Emission", type: "Noun", meaning: "নির্গমন", syn: "Release, Discharge" },
    { word: "Catastrophe", type: "Noun", meaning: "বিপর্যয়", syn: "Disaster, Calamity" },
    { word: "Extinction", type: "Noun", meaning: "বিলুপ্তি", syn: "Death, Destruction" },
    { word: "Deforestation", type: "Noun", meaning: "বন উজাড়", syn: "Logging, Clear-cutting" },
    { word: "Adaptation", type: "Noun", meaning: "অভিযোজন", syn: "Adjustment, Modification" },
    { word: "Sustainable", type: "Adj", meaning: "টেকসই", syn: "Maintainable, Eco-friendly" },
    { word: "Habitat", type: "Noun", meaning: "বাসস্থান", syn: "Environment, Home" },
    { word: "Unpredictable", type: "Adj", meaning: "অপ্রত্যাশিত", syn: "Uncertain, Erratic" },
    { word: "Mitigate", type: "Verb", meaning: "প্রশমিত করা / কমানো", syn: "Reduce, Lessen" },

    // Art, Music & Culture
    { word: "Craftsmanship", type: "Noun", meaning: "কারুশিল্প", syn: "Artistry, Skill" },
    { word: "Harmony", type: "Noun", meaning: "ঐকতান / মিল", syn: "Balance, Unity" },
    { word: "Aesthetic", type: "Adj", meaning: "নান্দনিক", syn: "Beautiful, Artistic" },
    { word: "Melody", type: "Noun", meaning: "সুরের মূর্ছনা", syn: "Tune, Song" },
    { word: "Rhythm", type: "Noun", meaning: "ছন্দ", syn: "Beat, Tempo" },
    { word: "Patriotism", type: "Noun", meaning: "দেশপ্রেম", syn: "Nationalism, Loyalty" },
    { word: "Folklore", type: "Noun", meaning: "লোককথা", syn: "Myth, Tradition" },
    { word: "Inspiration", type: "Noun", meaning: "অনুপ্রেরণা", syn: "Motivation, Encouragement" },
    { word: "Exhibition", type: "Noun", meaning: "প্রদর্শনী", syn: "Display, Show" },
    { word: "Masterpiece", type: "Noun", meaning: "অসাধারণ শিল্পকর্ম", syn: "Classic, Jewel" },

    // Education & Life Skills
    { word: "Etiquette", type: "Noun", meaning: "শিষ্টাচার", syn: "Manners, Politeness" },
    { word: "Institution", type: "Noun", meaning: "প্রতিষ্ঠান", syn: "Organization, Academy" },
    { word: "Illuminate", type: "Verb", meaning: "আলোকিত করা", syn: "Enlighten, Brighten" },
    { word: "Ignorance", type: "Noun", meaning: "অজ্ঞতা", syn: "Unawareness, Stupidity" },
    { word: "Tolerance", type: "Noun", meaning: "সহনশীলতা", syn: "Patience, Acceptance" },
    { word: "Compassion", type: "Noun", meaning: "করুণা", syn: "Pity, Sympathy" },
    { word: "Curriculum", type: "Noun", meaning: "পাঠ্যক্রম", syn: "Syllabus, Course" },
    { word: "Intellectual", type: "Adj", meaning: "বুদ্ধিবৃত্তিক", syn: "Mental, Scholarly" },
    { word: "Controversy", type: "Noun", meaning: "বিতর্ক", syn: "Argument, Dispute" },
    { word: "Obligation", type: "Noun", meaning: "বাধ্যবাধকতা", syn: "Duty, Responsibility" },

    // Myths & Legends
    { word: "Legendary", type: "Adj", meaning: "কিংবদন্তি", syn: "Famous, Mythical" },
    { word: "Heroic", type: "Adj", meaning: "বীরত্বপূর্ণ", syn: "Brave, Courageous" },
    { word: "Monstrous", type: "Adj", meaning: "দানবীয়", syn: "Terrifying, Huge" },
    { word: "Divine", type: "Adj", meaning: "স্বর্গীয় / ঐশ্বরিক", syn: "Holy, Sacred" },
    { word: "Prophecy", type: "Noun", meaning: "ভবিষ্যদ্বাণী", syn: "Prediction, Forecast" },
    { word: "Warrior", type: "Noun", meaning: "যোদ্ধা", syn: "Fighter, Soldier" },
    { word: "Invincible", type: "Adj", meaning: "অজেয়", syn: "Unbeatable, Indestructible" },
    { word: "Tragedy", type: "Noun", meaning: "বিয়োগান্তক ঘটনা", syn: "Disaster, Sorrow" },
    { word: "Epic", type: "Noun", meaning: "মহাকাব্য", syn: "Tale, Saga" },
    { word: "Immortal", type: "Adj", meaning: "অমর", syn: "Deathless, Eternal" },

    // Peace & Conflict
    { word: "Conflict", type: "Noun", meaning: "সংঘাত", syn: "Dispute, Battle" },
    { word: "Harmony", type: "Noun", meaning: "সম্প্রীতি", syn: "Peace, Unity" },
    { word: "Atrocity", type: "Noun", meaning: "নৃশংসতা", syn: "Cruelty, Horror" },
    { word: "Refugee", type: "Noun", meaning: "উদ্বাস্তু", syn: "Exile, Displaced person" },
    { word: "Treaty", type: "Noun", meaning: "চুক্তি", syn: "Agreement, Pact" },
    { word: "Diplomacy", type: "Noun", meaning: "কূটনীতি", syn: "Negotiation, Tact" },
    { word: "Aggression", type: "Noun", meaning: "আগ্রাসন", syn: "Hostility, Attack" },
    { word: "Genocide", type: "Noun", meaning: "গণহত্যা", syn: "Massacre, Slaughter" },
    { word: "Resolution", type: "Noun", meaning: "মীমাংসা", syn: "Decision, Settlement" },
    { word: "Alliance", type: "Noun", meaning: "জোট", syn: "Partnership, Coalition" },

    // Crucial Connectors & Modifiers (Part 2)
    { word: "Eventually", type: "Adverb", meaning: "অবশেষে", syn: "Finally, Ultimately" },
    { word: "Undoubtedly", type: "Adverb", meaning: "নিঃসন্দেহে", syn: "Certainly, Absolutely" },
    { word: "Ironically", type: "Adverb", meaning: "বিদ্রূপাত্মকভাবে", syn: "Paradoxically, Unexpectedly" },
    { word: "Apparently", type: "Adverb", meaning: "স্পষ্টতই", syn: "Seemingly, Evidently" },
    { word: "Gradually", type: "Adverb", meaning: "ধীরে ধীরে", syn: "Slowly, Steadily" },
    { word: "Consequently", type: "Adverb", meaning: "ফলস্বরূপ", syn: "Therefore, Thus" },
    { word: "Alternatively", type: "Adverb", meaning: "বিকল্প হিসেবে", syn: "Instead, Otherwise" },
    { word: "Predominantly", type: "Adverb", meaning: "প্রধানত", syn: "Mainly, Mostly" },
    { word: "Fundamentally", type: "Adverb", meaning: "মৌলিকভাবে", syn: "Basically, Essentially" },
    { word: "Crucially", type: "Adverb", meaning: "অত্যন্ত গুরুত্বপূর্ণভাবে", syn: "Vitally, Critically" },

    // Advanced Passage Adjectives
    { word: "Obsolete", type: "Adj", meaning: "সেকেলে / বাতিল", syn: "Outdated, Old-fashioned" },
    { word: "Lucrative", type: "Adj", meaning: "লাভজনক", syn: "Profitable, Rewarding" },
    { word: "Vast", type: "Adj", meaning: "বিশাল", syn: "Huge, Massive" },
    { word: "Scanty", type: "Adj", meaning: "অপ্রতুল / সামান্য", syn: "Scarce, Limited" },
    { word: "Spontaneous", type: "Adj", meaning: "স্বতঃস্ফূর্ত", syn: "Natural, Unplanned" },
    { word: "Authentic", type: "Adj", meaning: "খাঁটি", syn: "Genuine, Real" },
    { word: "Versatile", type: "Adj", meaning: "বহুমুখী", syn: "Adaptable, Multipurpose" },
    { word: "Fragile", type: "Adj", meaning: "ভঙ্গুর", syn: "Delicate, Breakable" },
    { word: "Tremendous", type: "Adj", meaning: "অসাধারণ / বিশাল", syn: "Enormous, Fantastic" },
    { word: "Vital", type: "Adj", meaning: "অত্যাবশ্যক", syn: "Crucial, Essential" }, 
    
];
