/* vocab.js - The Unlimited Word Database */

const vocabList = [
    { w: "Abolish", m: "বাতিল করা", s: "Cancel / Eliminate" },
    { w: "Abundant", m: "প্রচুর", s: "Plentiful / Copious" },
    { w: "Accelerate", m: "ত্বরান্বিত করা", s: "Speed up / Hasten" },
    { w: "Accommodation", m: "বাসস্থান", s: "Housing / Lodging" },
    { w: "Accomplish", m: "সম্পন্ন করা", s: "Achieve / Fulfill" },
    { w: "Accumulate", m: "জমা করা", s: "Gather / Collect" },
    { w: "Accurate", m: "সঠিক", s: "Exact / Precise" },
    { w: "Adequate", m: "পর্যাপ্ত", s: "Sufficient / Enough" },
    { w: "Adhere", m: "লেগে থাকা", s: "Stick / Cling" },
    { w: "Adjacent", m: "সংলগ্ন", s: "Next to / Adjoining" },
    { w: "Adulteration", m: "ভেজাল", s: "Contamination" },
    { w: "Adverse", m: "প্রতিকূল", s: "Unfavorable / Hostile" },
    { w: "Advocate", m: "সমর্থন করা / প্রবক্তা", s: "Support / Defender" },
    { w: "Aesthetic", m: "নান্দনিক", s: "Artistic / Beautiful" },
    { w: "Alleviate", m: "উপশম করা", s: "Relieve / Ease" },
    { w: "Allocate", m: "বরাদ্দ করা", s: "Assign / Distribute" },
    { w: "Alter", m: "পরিবর্তন করা", s: "Change / Modify" },
    { w: "Ambiguous", m: "অস্পষ্ট", s: "Unclear / Vague" },
    { w: "Ambition", m: "উচ্চাকাঙ্ক্ষা", s: "Aspiration / Goal" },
    { w: "Ample", m: "প্রচুর", s: "Plentiful / Abundant" },
    { w: "Analogy", m: "সাদৃশ্য", s: "Similarity / Comparison" },
    { w: "Anticipate", m: "প্রত্যাশা করা", s: "Expect / Predict" },
    { w: "Anxiety", m: "উদ্বেগ", s: "Worry / Unease" },
    { w: "Apparent", m: "স্পষ্ট", s: "Obvious / Evident" },
    { w: "Appropriate", m: "যথাযথ", s: "Suitable / Proper" },
    { w: "Arbitrary", m: "ইচ্ছামতো", s: "Random / Capricious" },
    { w: "Assemble", m: "একত্রিত করা", s: "Gather / Collect" },
    { w: "Assess", m: "মূল্যায়ন করা", s: "Evaluate / Judge" },
    { w: "Asset", m: "সম্পদ", s: "Property / Resource" },
    { w: "Assimilate", m: "গ্রহণ করা", s: "Absorb / Incorporate" },
    { w: "Astonish", m: "বিস্মিত করা", s: "Amaze / Surprise" },
    { w: "Attain", m: "অর্জন করা", s: "Achieve / Reach" },
    { w: "Authentic", m: "খাঁটি", s: "Real / Genuine" },
    { w: "Awe", m: "ভয়মিশ্রিত শ্রদ্ধা", s: "Wonder / Amazement" },
    { w: "Baffle", m: "হতবুদ্ধি করা", s: "Confuse / Puzzle" },
    { w: "Barren", m: "অনুর্বর", s: "Infertile / Empty" },
    { w: "Barrier", m: "বাধা", s: "Obstacle / Hurdle" },
    { w: "Benevolent", m: "পরোপকারী", s: "Kind / Generous" },
    { w: "Betray", m: "বিশ্বাসঘাতকতা করা", s: "Deceive / Cheat" },
    { w: "Bewilder", m: "বিভ্রান্ত করা", s: "Confuse / Baffle" },
    { w: "Bias", m: "পক্ষপাতিত্ব", s: "Prejudice / Partiality" },
    { w: "Bizarre", m: "অদ্ভুত", s: "Strange / Weird" },
    { w: "Brilliant", m: "মেধাবী", s: "Bright / Intelligent" },
    { w: "Brisk", m: "দ্রুত / চটপটে", s: "Quick / Energetic" },
    { w: "Brutal", m: "নিষ্ঠুর", s: "Cruel / Savage" },
    { w: "Calamity", m: "দুর্যোগ", s: "Disaster / Catastrophe" },
    { w: "Candid", m: "অকপট", s: "Frank / Honest" },
    { w: "Capacity", m: "ধারণক্ষমতা", s: "Ability / Volume" },
    { w: "Cautious", m: "সতর্ক", s: "Careful / Alert" },
    { w: "Cease", m: "থামা / বন্ধ করা", s: "Stop / Halt" },
    { w: "Chaos", m: "বিশৃঙ্খলা", s: "Disorder / Confusion" },
    { w: "Clarify", m: "স্পষ্ট করা", s: "Explain / Clear up" },
    { w: "Coherent", m: "সংলগ্ন / সামঞ্জস্যপূর্ণ", s: "Logical / Consistent" },
    { w: "Coincide", m: "একই সময়ে ঘটা", s: "Match / Occur together" },
    { w: "Collaborate", m: "সহযোগিতা করা", s: "Cooperate / Team up" },
    { w: "Colossal", m: "বিশাল", s: "Huge / Massive" },
    { w: "Commence", m: "শুরু করা", s: "Begin / Start" },
    { w: "Commend", m: "প্রশংসা করা", s: "Praise / Applaud" },
    { w: "Compassion", m: "সহমর্মিতা", s: "Pity / Sympathy" },
    { w: "Compel", m: "বাধ্য করা", s: "Force / Oblige" },
    { w: "Compensate", m: "ক্ষতিপূরণ দেওয়া", s: "Make up for / Repay" },
    { w: "Competent", m: "দক্ষ", s: "Capable / Skilled" },
    { w: "Compile", m: "সংকলন করা", s: "Gather / Assemble" },
    { w: "Complex", m: "জটিল", s: "Complicated / Intricate" },
    { w: "Comply", m: "মেনে চলা", s: "Obey / Conform" },
    { w: "Comprehend", m: "বুঝতে পারা", s: "Understand / Grasp" },
    { w: "Comprise", m: "গঠিত হওয়া", s: "Include / Contain" },
    { w: "Conceal", m: "লুকানো", s: "Hide / Cover" },
    { w: "Concede", m: "স্বীকার করা", s: "Admit / Yield" },
    { w: "Conclude", m: "উপসংহার টানা", s: "Finish / Decide" },
    { w: "Condemn", m: "নিন্দা করা", s: "Blame / Criticize" },
    { w: "Condense", m: "ঘনীভূত করা", s: "Compress / Shorten" },
    { w: "Confess", m: "স্বীকার করা", s: "Admit / Own up" },
    { w: "Confine", m: "সীমাবদ্ধ করা", s: "Restrict / Limit" },
    { w: "Confirm", m: "নিশ্চিত করা", s: "Verify / Approve" },
    { w: "Conflict", m: "দ্বন্দ্ব", s: "Clash / Dispute" },
    { w: "Conform", m: "মেনে চলা", s: "Adapt / Comply" },
    { w: "Confront", m: "মুখোমুখি হওয়া", s: "Face / Challenge" },
    { w: "Consequence", m: "পরিণাম", s: "Result / Outcome" },
    { w: "Conserve", m: "সংরক্ষণ করা", s: "Preserve / Save" },
    { w: "Considerable", m: "বিবেচনাযোগ্য", s: "Significant / Large" },
    { w: "Consistent", m: "ধারাবাহিক", s: "Steady / Reliable" },
    { w: "Conspicuous", m: "সুস্পষ্ট", s: "Noticeable / Obvious" },
    { w: "Constant", m: "ধ্রুবক", s: "Continuous / Steady" },
    { w: "Contaminate", m: "দূষিত করা", s: "Pollute / Infect" },
    { w: "Contemplate", m: "চিন্তা করা", s: "Ponder / Think" },
    { w: "Contemporary", m: "সমসাময়িক", s: "Modern / Current" },
    { w: "Contempt", m: "অবজ্ঞা", s: "Disdain / Scorn" },
    { w: "Contradict", m: "বিরোধিতা করা", s: "Oppose / Deny" },
    { w: "Contrast", m: "বৈসাদৃশ্য", s: "Difference / Comparison" },
    { w: "Contribute", m: "অবদান রাখা", s: "Donate / Supply" },
    { w: "Controversy", m: "বিতর্ক", s: "Dispute / Argument" },
    { w: "Convenient", m: "সুবিধাজনক", s: "Handy / Useful" },
    { w: "Converge", m: "একত্রিত হওয়া", s: "Meet / Join" },
    { w: "Convert", m: "রূপান্তর করা", s: "Change / Transform" },
    { w: "Convey", m: "জ্ঞাপন করা", s: "Communicate / Transfer" },
    { w: "Convince", m: "প্ররোচিত করা", s: "Persuade / Assure" },
    { w: "Cooperate", m: "সহযোগিতা করা", s: "Collaborate / Assist" },
    { w: "Copious", m: "প্রচুর", s: "Abundant / Plentiful" },
    { w: "Cordial", m: "আন্তরিক", s: "Friendly / Warm" },
    { w: "Crucial", m: "অত্যন্ত গুরুত্বপূর্ণ", s: "Critical / Essential" },
    { w: "Crude", m: "অশোধিত", s: "Raw / Unrefined" },
    { w: "Cruel", m: "নিষ্ঠুর", s: "Brutal / Harsh" },
    { w: "Culprit", m: "অপরাধী", s: "Offender / Criminal" },
    { w: "Cultivate", m: "চাষ করা", s: "Grow / Farm" },
    { w: "Cumulative", m: "ক্রমবর্ধমান", s: "Increasing / Growing" },
    { w: "Cunning", m: "ধূর্ত", s: "Sly / Clever" },
    { w: "Curious", m: "কৌতূহলী", s: "Inquisitive / Eager" },
    { w: "Cynical", m: "নিন্দুক", s: "Skeptical / Pessimistic" },
    { w: "Deceit", m: "প্রতারণা", s: "Fraud / Trickery" },
    { w: "Decline", m: "হ্রাস পাওয়া / প্রত্যাখ্যান", s: "Decrease / Refuse" },
    { w: "Deduce", m: "অনুমান করা", s: "Infer / Conclude" },
    { w: "Defect", m: "ত্রুটি", s: "Fault / Flaw" },
    { w: "Defend", m: "রক্ষা করা", s: "Protect / Guard" },
    { w: "Deficiency", m: "ঘাটতি", s: "Shortage / Lack" },
    { w: "Deliberate", m: "ইচ্ছাকৃত", s: "Intentional / Purposeful" },
    { w: "Delicate", m: "কোমল", s: "Fragile / Gentle" },
    { w: "Demonstrate", m: "প্রদর্শন করা", s: "Show / Reveal" },
    { w: "Deny", m: "অস্বীকার করা", s: "Reject / Refuse" },
    { w: "Deplete", m: "নিঃশেষ করা", s: "Empty / Exhaust" },
    { w: "Deprive", m: "বঞ্চিত করা", s: "Rob / Strip" },
    { w: "Descend", m: "অবতরণ করা", s: "Go down / Drop" },
    { w: "Desire", m: "বাসনা", s: "Wish / Want" },
    { w: "Despair", m: "হতাশা", s: "Hopelessness / Gloom" },
    { w: "Despise", m: "ঘৃণা করা", s: "Hate / Loathe" },
    { w: "Destiny", m: "ভাগ্য", s: "Fate / Fortune" },
    { w: "Destroy", m: "ধ্বংস করা", s: "Ruin / Demolish" },
    { w: "Detect", m: "শনাক্ত করা", s: "Discover / Notice" },
    { w: "Deteriorate", m: "অবনতি হওয়া", s: "Worsen / Decline" },
    { w: "Determine", m: "নির্ধারণ করা", s: "Decide / Resolve" },
    { w: "Detrimental", m: "ক্ষতিকর", s: "Harmful / Damaging" },
    { w: "Devastate", m: "বিধ্বস্ত করা", s: "Destroy / Ruin" },
    { w: "Deviate", m: "বিচ্যুত হওয়া", s: "Stray / Diverge" },
    { w: "Devote", m: "উৎসর্গ করা", s: "Dedicate / Commit" },
    { w: "Diligent", m: "পরিশ্রমী", s: "Hardworking / Industrious" },
    { w: "Diminish", m: "হ্রাস করা", s: "Decrease / Reduce" },
    { w: "Disaster", m: "বিপর্যয়", s: "Catastrophe / Calamity" },
    { w: "Disclose", m: "প্রকাশ করা", s: "Reveal / Uncover" },
    { w: "Discrimination", m: "বৈষম্য", s: "Bias / Prejudice" },
    { w: "Disgust", m: "বিরক্তি", s: "Repulsion / Loathing" },
    { w: "Dismay", m: "হতাশ করা", s: "Disappoint / Shock" },
    { w: "Disperse", m: "ছড়িয়ে দেওয়া", s: "Scatter / Spread" },
    { w: "Dispute", m: "বিরোধ", s: "Argument / Conflict" },
    { w: "Distinct", m: "স্বতন্ত্র", s: "Clear / Different" },
    { w: "Distinguish", m: "পার্থক্য করা", s: "Differentiate / Separate" },
    { w: "Distort", m: "বিকৃত করা", s: "Twist / Deform" },
    { w: "Distract", m: "মনোযোগ সরানো", s: "Divert / Confuse" },
    { w: "Diverse", m: "বৈচিত্র্যময়", s: "Various / Different" },
    { w: "Divert", m: "গতি পরিবর্তন করা", s: "Redirect / Deflect" },
    { w: "Divine", m: "স্বর্গীয়", s: "Heavenly / Holy" },
    { w: "Dominant", m: "প্রভাবশালী", s: "Controlling / Leading" },
    { w: "Donate", m: "দান করা", s: "Give / Contribute" },
    { w: "Doubt", m: "সন্দেহ", s: "Uncertainty / Suspicion" },
    { w: "Drastic", m: "কঠোর", s: "Extreme / Severe" },
    { w: "Dread", m: "ভয়", s: "Fear / Terror" },
    { w: "Dubious", m: "সন্দেহজনক", s: "Doubtful / Uncertain" },
    { w: "Dull", m: "নীরস", s: "Boring / Tedious" },
    { w: "Dumb", m: "বোবা", s: "Mute / Speechless" },
    { w: "Dynamic", m: "গতিশীল", s: "Active / Energetic" },
    { w: "Eager", m: "আগ্রহী", s: "Keen / Enthusiastic" },
    { w: "Earnest", m: "আন্তরিক", s: "Serious / Sincere" },
    { w: "Eccentric", m: "অদ্ভুতস্বভাব", s: "Odd / Strange" },
    { w: "Ecstasy", m: "পরমানন্দ", s: "Joy / Rapture" },
    { w: "Edible", m: "ভোজ্য", s: "Eatable / Safe to eat" },
    { w: "Effort", m: "প্রচেষ্টা", s: "Attempt / Endeavor" },
    { w: "Ego", m: "অহংকার", s: "Pride / Self-esteem" },
    { w: "Elaborate", m: "বিস্তারিত", s: "Detailed / Intricate" },
    { w: "Elevate", m: "উত্তোলন করা", s: "Raise / Lift" },
    { w: "Elicit", m: "বের করে আনা", s: "Extract / Obtain" },
    { w: "Eligible", m: "যোগ্য", s: "Qualified / Suitable" },
    { w: "Eliminate", m: "বর্জন করা", s: "Remove / Eradicate" },
    { w: "Elite", m: "অভিজাত", s: "Top / Best" },
    { w: "Eloquence", m: "বাগ্মিতা", s: "Fluency / Expressiveness" },
    { w: "Emancipate", m: "মুক্ত করা", s: "Liberate / Free" },
    { w: "Embark", m: "শুরু করা", s: "Begin / Start" },
    { w: "Embrace", m: "আলিঙ্গন করা / গ্রহণ করা", s: "Hug / Accept" },
    { w: "Emerge", m: "আবির্ভূত হওয়া", s: "Appear / Arise" },
    { w: "Eminent", m: "প্রখ্যাত", s: "Famous / Distinguished" },
    { w: "Emit", m: "নির্গমন করা", s: "Release / Discharge" },
    { w: "Emotion", m: "আবেগ", s: "Feeling / Passion" },
    { w: "Empathy", m: "সহমর্মিতা", s: "Understanding / Compassion" },
    { w: "Emphasis", m: "জোর দেওয়া", s: "Stress / Importance" },
    { w: "Empower", m: "ক্ষমতায়ন করা", s: "Authorize / Enable" },
    { w: "Encounter", m: "সম্মুখীন হওয়া", s: "Meet / Face" },
    { w: "Endeavor", m: "প্রচেষ্টা", s: "Attempt / Effort" },
    { w: "Endorse", m: "অনুমোদন করা", s: "Approve / Support" },
    { w: "Endure", m: "সহ্য করা", s: "Bear / Tolerate" },
    { w: "Enforce", m: "কার্যকর করা", s: "Impose / Apply" },
    { w: "Engage", m: "জড়িত থাকা", s: "Involve / Participate" },
    { w: "Enhance", m: "উন্নত করা", s: "Improve / Boost" },
    { w: "Enormous", m: "বিশাল", s: "Huge / Vast" },
    { w: "Ensure", m: "নিশ্চিত করা", s: "Guarantee / Make certain" },
    { w: "Enthusiasm", m: "প্রবল উৎসাহ", s: "Zeal / Eagerness" },
    { w: "Equitable", m: "ন্যায়সঙ্গত", s: "Fair / Just" },
    { w: "Eradicate", m: "নির্মূল করা", s: "Eliminate / Destroy" },
    { w: "Erratic", m: "অনিয়মিত", s: "Unpredictable / Irregular" },
    { w: "Essential", m: "অপরিহার্য", s: "Vital / Crucial" }, 
    { w: "Evaluate", m: "মূল্যায়ন করা", s: "Assess / Judge" },
    { w: "Evident", m: "স্পষ্ট", s: "Obvious / Apparent" },
    { w: "Exaggerate", m: "অতিরঞ্জিত করা", s: "Overstate / Magnify" },
    { w: "Exceed", m: "অতিক্রম করা", s: "Surpass / Outdo" },
    { w: "Exceptional", m: "ব্যতিক্রমী", s: "Outstanding / Extraordinary" },
    { w: "Execute", m: "সম্পাদন করা", s: "Perform / Implement" },
    { w: "Exhaust", m: "নিঃশেষ করা", s: "Deplete / Drain" },
    { w: "Exile", m: "নির্বাসন", s: "Banishment / Expulsion" },
    { w: "Expand", m: "সম্প্রসারিত করা", s: "Enlarge / Increase" },
    { w: "Explicit", m: "সুস্পষ্ট", s: "Clear / Exact" },
    { w: "Exploit", m: "শোষণ করা / কাজে লাগানো", s: "Utilize / Abuse" },
    { w: "Extensive", m: "ব্যাপক", s: "Vast / Widespread" },
    { w: "Fabricate", m: "নির্মাণ করা / জালিয়াতি করা", s: "Construct / Forge" },
    { w: "Facilitate", m: "সহজতর করা", s: "Ease / Assist" },
    { w: "Fascinate", m: "মুগ্ধ করা", s: "Charm / Captivate" },
    { w: "Fatal", m: "মারাত্মক", s: "Deadly / Lethal" },
    { w: "Fatigue", m: "ক্লান্তি", s: "Tiredness / Exhaustion" },
    { w: "Fierce", m: "ভয়ঙ্কর", s: "Ferocious / Aggressive" },
    { w: "Flexible", m: "নমনীয়", s: "Adaptable / Pliable" },
    { w: "Flourish", m: "সমৃদ্ধ হওয়া", s: "Thrive / Prosper" },
    { w: "Fluctuate", m: "ওঠানামা করা", s: "Vary / Swing" },
    { w: "Foresee", m: "আগে থেকে দেখা", s: "Predict / Anticipate" },
    { w: "Forge", m: "জাল করা / গড়া", s: "Counterfeit / Create" },
    { w: "Formidable", m: "ভয়ঙ্কর / দুর্দান্ত", s: "Intimidating / Impressive" },
    { w: "Foster", m: "লালনপালন করা", s: "Nurture / Encourage" },
    { w: "Fragile", m: "ভঙ্গুর", s: "Delicate / Breakable" },
    { w: "Frequent", m: "ঘন ঘন", s: "Regular / Repeated" },
    { w: "Frustrate", m: "হতাশ করা", s: "Disappoint / Thwart" },
    { w: "Fundamental", m: "মৌলিক", s: "Basic / Essential" },
    { w: "Furious", m: "ক্ষীপ্ত / প্রচণ্ড", s: "Enraged / Violent" },
    { w: "Generate", m: "উৎপাদন করা", s: "Produce / Create" },
    { w: "Genuine", m: "খাঁটি", s: "Authentic / Real" },
    { w: "Gigantic", m: "বিশাল", s: "Huge / Enormous" },
    { w: "Glimpse", m: "একঝলক দেখা", s: "Glance / Peek" },
    { w: "Gloomy", m: "বিষণ্ণ", s: "Dark / Depressing" },
    { w: "Glorious", m: "গৌরবময়", s: "Magnificent / Splendid" },
    { w: "Gratitude", m: "কৃতজ্ঞতা", s: "Thankfulness / Appreciation" },
    { w: "Grief", m: "দুঃখ", s: "Sorrow / Sadness" },
    { w: "Guarantee", m: "নিশ্চয়তা দেওয়া", s: "Assure / Warrant" },
    { w: "Guilty", m: "দোষী", s: "Culpable / Blameable" },
    { w: "Halt", m: "থামানো", s: "Stop / Pause" },
    { w: "Hazard", m: "বিপদ", s: "Danger / Risk" },
    { w: "Hesitate", m: "ইতস্তত করা", s: "Pause / Delay" },
    { w: "Hilarious", m: "হাস্যকর", s: "Amusing / Funny" },
    { w: "Hinder", m: "বাধা দেওয়া", s: "Obstruct / Impede" },
    { w: "Hostile", m: "শত্রুভাবাপন্ন", s: "Unfriendly / Aggressive" },
    { w: "Huge", m: "বিশাল", s: "Vast / Gigantic" },
    { w: "Humane", m: "মানবিক", s: "Kind / Compassionate" },
    { w: "Humble", m: "বিনীত", s: "Modest / Meek" },
    { w: "Hypocrisy", m: "ভণ্ডামি", s: "Deceit / Insincerity" },
    { w: "Identify", m: "শনাক্ত করা", s: "Recognize / Spot" },
    { w: "Ignite", m: "জ্বালানো", s: "Light / Kindle" },
    { w: "Ignore", m: "উপেক্ষা করা", s: "Disregard / Neglect" },
    { w: "Illiterate", m: "নিরক্ষর", s: "Uneducated / Ignorant" },
    { w: "Illusion", m: "ভ্রম", s: "Mirage / Hallucination" },
    { w: "Illustrate", m: "দৃষ্টান্ত দিয়ে বোঝানো", s: "Explain / Demonstrate" },
    { w: "Immense", m: "প্রচুর", s: "Huge / Massive" },
    { w: "Imminent", m: "আসন্ন", s: "Approaching / Impending" },
    { w: "Impact", m: "প্রভাব", s: "Effect / Influence" },
    { w: "Impartial", m: "নিরপেক্ষ", s: "Fair / Unbiased" },
    { w: "Implement", m: "বাস্তবায়ন করা", s: "Execute / Apply" },
    { w: "Impose", m: "চাপিয়ে দেওয়া", s: "Force / Enforce" },
    { w: "Impulse", m: "প্রবণতা / ঝোঁক", s: "Urge / Instinct" },
    { w: "Inadequate", m: "অপর্যাপ্ত", s: "Insufficient / Lacking" },
    { w: "Incentive", m: "উদ্দীপনা", s: "Motivation / Encouragement" },
    { w: "Incident", m: "ঘটনা", s: "Event / Occurrence" },
    { w: "Incline", m: "ঝোঁক", s: "Lean / Tendency" },
    { w: "Incorporate", m: "অন্তর্ভুক্ত করা", s: "Include / Integrate" },
    { w: "Incredible", m: "অবিশ্বাস্য", s: "Unbelievable / Amazing" },
    { w: "Indicate", m: "নির্দেশ করা", s: "Show / Point out" },
    { w: "Indispensable", m: "অপরিহার্য", s: "Essential / Crucial" },
    { w: "Inevitable", m: "অনিবার্য", s: "Unavoidable / Certain" },
    { w: "Infect", m: "সংক্রমিত করা", s: "Contaminate / Taint" },
    { w: "Infer", m: "অনুমান করা", s: "Deduce / Conclude" },
    { w: "Infinite", m: "অসীম", s: "Endless / Limitless" },
    { w: "Influence", m: "প্রভাব", s: "Impact / Effect" },
    { w: "Inherent", m: "সহজাত", s: "Innate / Built-in" },
    { w: "Initiate", m: "সূচনা করা", s: "Start / Begin" },
    { w: "Injure", m: "আহত করা", s: "Hurt / Harm" },
    { w: "Innocent", m: "নির্দোষ", s: "Guiltless / Pure" },
    { w: "Innovate", m: "উদ্ভাবন করা", s: "Invent / Create" },
    { w: "Inquire", m: "জিজ্ঞাসা করা", s: "Ask / Investigate" },
    { w: "Insane", m: "পাগল", s: "Crazy / Mad" },
    { w: "Insert", m: "প্রবেশ করানো", s: "Put in / Embed" },
    { w: "Insight", m: "অন্তর্দৃষ্টি", s: "Understanding / Perception" },
    { w: "Insist", m: "জোর দেওয়া", s: "Demand / Urge" },
    { w: "Inspect", m: "তদন্ত করা", s: "Examine / Check" },
    { w: "Inspire", m: "অনুপ্রাণিত করা", s: "Motivate / Encourage" },
    { w: "Install", m: "স্থাপন করা", s: "Set up / Put in" },
    { w: "Instance", m: "ঘটনা", s: "Example / Case" },
    { w: "Instinct", m: "সহজাত প্রবৃত্তি", s: "Intuition / Natural feeling" },
    { w: "Integrate", m: "সমন্বয় করা", s: "Combine / Unite" },
    { w: "Intense", m: "তীব্র", s: "Extreme / Strong" },
    { w: "Interfere", m: "হস্তক্ষেপ করা", s: "Meddle / Intervene" },
    { w: "Interpret", m: "ব্যাখ্যা করা", s: "Explain / Understand" },
    { w: "Interrupt", m: "বাধা দেওয়া", s: "Break in / Disturb" },
    { w: "Intervene", m: "হস্তক্ষেপ করা", s: "Step in / Interfere" },
    { w: "Intimate", m: "অন্তরঙ্গ", s: "Close / Familiar" },
    { w: "Intimidate", m: "ভয় দেখানো", s: "Frighten / Scare" },
    { w: "Intricate", m: "জটিল", s: "Complex / Complicated" },
    { w: "Intrigue", m: "কৌতূহলী করা", s: "Fascinate / Plot" },
    { w: "Invade", m: "আক্রমণ করা", s: "Attack / Occupy" },
    { w: "Investigate", m: "তদন্ত করা", s: "Examine / Explore" },
    { w: "Invoke", m: "আহ্বান করা", s: "Call upon / Appeal" },
    { w: "Involve", m: "জড়িত করা", s: "Include / Engage" },
    { w: "Isolate", m: "বিচ্ছিন্ন করা", s: "Separate / Detach" },
    { w: "Jeopardize", m: "বিপন্ন করা", s: "Endanger / Risk" },
    { w: "Justify", m: "ন্যায্য প্রমাণ করা", s: "Defend / Prove right" },
    { w: "Keen", m: "প্রখর / আগ্রহী", s: "Eager / Sharp" },
    { w: "Knowledge", m: "জ্ঞান", s: "Information / Understanding" },
    { w: "Laborious", m: "কঠোর পরিশ্রমী", s: "Hardworking / Difficult" },
    { w: "Lament", m: "বিলাপ করা", s: "Mourn / Grieve" },
    { w: "Launch", m: "শুরু করা", s: "Start / Initiate" },
    { w: "Lavish", m: "বিলাসবহুল", s: "Luxurious / Extravagant" },
    { w: "Legacy", m: "ঐতিহ্য", s: "Heritage / Tradition" },
    { w: "Legitimate", m: "বৈধ", s: "Legal / Valid" },
    { w: "Lethal", m: "প্রাণঘাতী", s: "Deadly / Fatal" },
    { w: "Liberate", m: "মুক্ত করা", s: "Free / Emancipate" },
    { w: "Logic", m: "যুক্তি", s: "Reason / Sense" },
    { w: "Lucid", m: "সহজবোধ্য", s: "Clear / Plain" },
    { w: "Magnificent", m: "চমৎকার", s: "Splendid / Grand" },
    { w: "Maintain", m: "বজায় রাখা", s: "Keep / Preserve" },
    { w: "Majestic", m: "রাজকীয়", s: "Grand / Impressive" },
    { w: "Mandatory", m: "বাধ্যতামূলক", s: "Required / Compulsory" },
    { w: "Manifest", m: "প্রকাশ করা", s: "Display / Show" },
    { w: "Manipulate", m: "নিপুণভাবে পরিচালনা করা", s: "Control / Handle" },
    { w: "Margin", m: "প্রান্ত", s: "Edge / Border" },
    { w: "Marvelous", m: "অপূর্ব", s: "Wonderful / Amazing" },
    { w: "Massive", m: "বিশাল", s: "Huge / Enormous" },
    { w: "Maximum", m: "সর্বোচ্চ", s: "Most / Highest" },
    { w: "Meager", m: "অপ্রতুল", s: "Scanty / Sparse" },
    { w: "Meditate", m: "ধ্যান করা", s: "Ponder / Think" },
    { w: "Menace", m: "বিপদ", s: "Danger / Threat" },
    { w: "Merge", m: "একত্রিত করা", s: "Combine / Join" },
    { w: "Merit", m: "যোগ্যতা", s: "Worth / Value" },
    { w: "Mighty", m: "শক্তিশালী", s: "Powerful / Strong" },
    { w: "Migrate", m: "স্থানান্তর করা", s: "Move / Relocate" },
    { w: "Miniature", m: "ক্ষুদ্র", s: "Tiny / Small" },
    { w: "Minimum", m: "সর্বনিম্ন", s: "Least / Lowest" },
    { w: "Minor", m: "নগণ্য", s: "Small / Insignificant" },
    { w: "Miracle", m: "অলৌকিক ঘটনা", s: "Wonder / Marvel" },
    { w: "Miserable", m: "দুর্দশাগ্রস্ত", s: "Unhappy / Wretched" },
    { w: "Mislead", m: "ভুল পথে চালিত করা", s: "Deceive / Guide astray" },
    { w: "Mitigate", m: "হ্রাস করা", s: "Alleviate / Lessen" },
    { w: "Modify", m: "পরিবর্তন করা", s: "Alter / Change" },
    { w: "Monstrous", m: "দানবীয়", s: "Huge / Hideous" },
    { w: "Moral", m: "নৈতিক", s: "Ethical / Good" },
    { w: "Mortal", m: "মরণশীল", s: "Fatal / Human" },
    { w: "Motive", m: "উদ্দেশ্য", s: "Reason / Purpose" },
    { w: "Multiply", m: "বৃদ্ধি করা", s: "Increase / Reproduce" },
    { w: "Mutual", m: "পারস্পরিক", s: "Shared / Common" },
    { w: "Mysterious", m: "রহস্যময়", s: "Secret / Puzzling" },
    { w: "Narrate", m: "বর্ণনা করা", s: "Tell / Relate" },
    { w: "Native", m: "দেশীয়", s: "Indigenous / Local" },
    { w: "Navigate", m: "পথ প্রদর্শন করা", s: "Steer / Direct" },
    { w: "Necessity", m: "প্রয়োজনীয়তা", s: "Need / Requirement" },
    { w: "Neglect", m: "অবহেলা করা", s: "Ignore / Disregard" },
    { w: "Negotiate", m: "মীমাংসা করা", s: "Bargain / Discuss" },
    { w: "Neutral", m: "নিরপেক্ষ", s: "Impartial / Unbiased" },
    { w: "Noble", m: "মহান", s: "Honorable / Aristocratic" },
    { w: "Nominate", m: "মনোনীত করা", s: "Appoint / Choose" },
    { w: "Notable", m: "লক্ষণীয়", s: "Remarkable / Outstanding" },
    { w: "Notorious", m: "কুখ্যাত", s: "Infamous / Disreputable" },
    { w: "Numerous", m: "অসংখ্য", s: "Many / Countless" },
    { w: "Obedient", m: "বাধ্য", s: "Compliant / Respectful" },
    { w: "Object", m: "আপত্তি করা / বস্তু", s: "Protest / Thing" },
    { w: "Obligate", m: "বাধ্য করা", s: "Force / Require" },
    { w: "Obscure", m: "অস্পষ্ট", s: "Unclear / Hidden" },
    { w: "Observe", m: "পর্যবেক্ষণ করা", s: "Notice / Watch" },
    { w: "Obsolete", m: "অপ্রচলিত", s: "Outdated / Old-fashioned" },
    { w: "Obstacle", m: "বাধা", s: "Barrier / Hurdle" },
    { w: "Obtain", m: "পাওয়া", s: "Get / Acquire" },
    { w: "Obvious", m: "স্পষ্ট", s: "Clear / Evident" },
    { w: "Occupy", m: "দখল করা", s: "Inhabit / Invade" },
    { w: "Offend", m: "অপমান করা", s: "Insult / Displease" },
    { w: "Omit", m: "বাদ দেওয়া", s: "Leave out / Exclude" },
    { w: "Opaque", m: "অস্বচ্ছ", s: "Cloudy / Unclear" },
    { w: "Operate", m: "পরিচালনা করা", s: "Run / Manage" },
    { w: "Opponent", m: "প্রতিপক্ষ", s: "Rival / Enemy" },
    { w: "Opportunity", m: "সুযোগ", s: "Chance / Opening" },
    { w: "Oppose", m: "বিরোধিতা করা", s: "Resist / Fight" },
    { w: "Optimistic", m: "আশাবাদী", s: "Hopeful / Positive" },
    { w: "Option", m: "বিকল্প", s: "Choice / Alternative" },
    { w: "Ordinary", m: "সাধারণ", s: "Normal / Common" },
    { w: "Origin", m: "উৎস", s: "Source / Beginning" },
    { w: "Outcome", m: "ফলাফল", s: "Result / Consequence" },
    { w: "Outrageous", m: "জঘন্য", s: "Shocking / Scandalous" },
    { w: "Outstanding", m: "অসাধারণ", s: "Excellent / Exceptional" },
    { w: "Overcome", m: "পরাস্ত করা", s: "Conquer / Defeat" },
    { w: "Overlook", m: "উপেক্ষা করা", s: "Miss / Ignore" }
];
