/* vocab.js - The Unlimited Word Database */

const vocabList = [
    // --- SET 1: CRITICAL HSC WORDS ---
    { w: "Adulteration", m: "ভেজাল", s: "Contamination" },
    { w: "Ambition", m: "উচ্চাকাঙ্ক্ষা", s: "Aspiration / Goal" },
    { w: "Amenity", m: "সুযোগ-সুবিধা", s: "Facility / Comfort" },
    { w: "Analogy", m: "সাদৃশ্য", s: "Similarity" },
    { w: "Anticipate", m: "প্রত্যাশা করা", s: "Expect / Predict" },
    { w: "Apparent", m: "স্পষ্ট", s: "Obvious / Evident" },
    { w: "Arbitrary", m: "ইচ্ছামতো", s: "Random / Whimsical" },
    { w: "Benevolent", m: "পরোপকারী", s: "Kind / Generous" },
    { w: "Bizarre", m: "অদ্ভুত", s: "Strange / Weird" },
    { w: "Calamity", m: "দুর্যোগ", s: "Disaster / Catastrophe" },
    { w: "Chaos", m: "বিশৃঙ্খলা", s: "Disorder / Confusion" },
    { w: "Commence", m: "শুরু করা", s: "Start / Begin" },
    { w: "Compassion", m: "সহমর্মিতা", s: "Empathy / Kindness" },
    { w: "Consent", m: "সম্মতি", s: "Agreement / Permission" },
    { w: "Consequence", m: "পরিণাম", s: "Result / Outcome" },
    { w: "Conserve", m: "সংরক্ষণ করা", s: "Preserve / Save" },
    { w: "Contemporary", m: "সমসাময়িক", s: "Modern / Current" },
    { w: "Contradict", m: "বিরোধিতা করা", s: "Oppose / Deny" },
    { w: "Curriculum", m: "পাঠ্যক্রম", s: "Syllabus" },
    { w: "Debate", m: "বিতর্ক", s: "Argument / Discussion" },
    { w: "Decline", m: "হ্রাস পাওয়া", s: "Decrease / Refuse" },
    { w: "Deficiency", m: "ঘাটতি", s: "Shortage / Lack" },
    { w: "Diligent", m: "পরিশ্রমী", s: "Hardworking" },
    { w: "Discrimination", m: "বৈষম্য", s: "Bias / Prejudice" },
    { w: "Diverse", m: "বিচিত্র", s: "Varied / Different" },
    { w: "Dynamic", m: "গতিশীল", s: "Active / Energetic" },
    { w: "Ecological", m: "বাস্তুতান্ত্রিক", s: "Environmental" },
    { w: "Eliminate", m: "বর্জন করা", s: "Remove / Eradicate" },
    { w: "Emancipation", m: "মুক্তি", s: "Liberation / Freedom" },
    { w: "Enthusiasm", m: "উৎসাহ", s: "Zeal / Eagerness" },
    { w: "Essential", m: "অপরিহার্য", s: "Necessary / Vital" },
    { w: "Evident", m: "প্রতীয়মান", s: "Clear / Plain" },
    { w: "Exhausted", m: "নিঃশেষিত", s: "Tired / Drained" },
    { w: "Extinct", m: "বিলুপ্ত", s: "Vanished" },
    { w: "Fascinating", m: "আকর্ষণীয়", s: "Captivating" },
    { w: "Fragile", m: "ভঙ্গুর", s: "Delicate / Weak" },
    { w: "Genuine", m: "খাঁটি", s: "Real / Authentic" },
    { w: "Gesture", m: "অঙ্গভঙ্গি", s: "Signal / Motion" },
    { w: "Global", m: "বৈশ্বিক", s: "Worldwide" },
    { w: "Harmony", m: "সম্প্রীতি", s: "Peace / Accord" },
    { w: "Humiliation", m: "অপমান", s: "Insult / Shame" },
    { w: "Hypocrisy", m: "ভণ্ডামি", s: "Insincerity" },
    { w: "Illiterate", m: "নিরক্ষর", s: "Uneducated" },
    { w: "Imitate", m: "অনুকরণ করা", s: "Copy / Mimic" },
    { w: "Immense", m: "বিশাল", s: "Huge / Massive" },
    { w: "Impact", m: "প্রভাব", s: "Effect / Influence" },
    { w: "Impartial", m: "নিরপেক্ষ", s: "Neutral / Fair" },
    { w: "Indifferent", m: "উদাসীন", s: "Unconcerned" },
    { w: "Inevitable", m: "অনিবার্য", s: "Unavoidable" },
    { w: "Initiative", m: "উদ্যোগ", s: "Step / Action" },
    { w: "Inspire", m: "অনুপ্রাণিত করা", s: "Motivate / Encourage" },
    { w: "Integrity", m: "সততা", s: "Honesty / Morality" },
    { w: "Intense", m: "তীব্র", s: "Extreme / Strong" },
    { w: "Judicious", m: "বিচক্ষণ", s: "Wise / Prudent" },
    { w: "Keen", m: "আগ্রহী", s: "Eager / Sharp" },
    { w: "Legacy", m: "ঐতিহ্য", s: "Heritage" },
    { w: "Leisure", m: "অবসর", s: "Free time" },
    { w: "Lucid", m: "স্পষ্ট", s: "Clear" },
    { w: "Magnificent", m: "চমৎকার", s: "Splendid / Grand" },
    { w: "Mandatory", m: "বাধ্যতামূলক", s: "Compulsory" },
    { w: "Narrate", m: "বর্ণনা করা", s: "Tell / Describe" },
    { w: "Native", m: "দেশীয়", s: "Indigenous / Local" },
    { w: "Negligence", m: "অবহেলা", s: "Carelessness" },
    { w: "Nostalgia", m: "অতীত স্মৃতি", s: "Reminiscence" },
    { w: "Notorious", m: "কুখ্যাত", s: "Infamous" },
    { w: "Novice", m: "নবিশ", s: "Beginner" },
    { w: "Obligation", m: "বাধ্যবাধকতা", s: "Duty / Responsibility" },
    { w: "Obscure", m: "অস্পষ্ট", s: "Unclear / Vague" },
    { w: "Obstacle", m: "বাধা", s: "Barrier / Hurdle" },
    { w: "Optimistic", m: "আশাবাদী", s: "Hopeful" },
    { w: "Outrageous", m: "আপত্তিকর", s: "Shocking" },
    { w: "Overcome", m: "জয় করা", s: "Conquer / Defeat" },
    { w: "Participate", m: "অংশগ্রহণ করা", s: "Take part" },
    { w: "Patriotism", m: "দেশপ্রেম", s: "Nationalism" },
    { w: "Poverty", m: "দারিদ্র্য", s: "Destitution" },
    { w: "Pragmatic", m: "বাস্তববাদী", s: "Practical" },
    { w: "Precise", m: "নির্ভুল", s: "Exact / Accurate" },
    { w: "Predicament", m: "দশা/বিপদ", s: "Dilemma / Plight" },
    { w: "Prejudice", m: "কুসংস্কার", s: "Bias" },
    { w: "Preserve", m: "রক্ষা করা", s: "Protect / Save" },
    { w: "Prevalent", m: "প্রচলিত", s: "Common / Widespread" },
    { w: "Primitive", m: "আদিম", s: "Ancient / Early" },
    { w: "Prohibit", m: "নিষেধ করা", s: "Forbid / Ban" },
    { w: "Prominent", m: "বিশিষ্ট", s: "Famous / Notable" },
    { w: "Prosperity", m: "সমৃদ্ধি", s: "Success / Wealth" },
    { w: "Protest", m: "প্রতিবাদ", s: "Object / Oppose" },
    { w: "Prudent", m: "বিচক্ষণ", s: "Wise / Careful" },
    { w: "Punctual", m: "সময়ানুবর্তী", s: "Timely" },
    { w: "Quench", m: "নিবৃত্ত করা", s: "Satisfy (thirst)" },
    { w: "Radical", m: "চরমপন্থী", s: "Extreme" },
    { w: "Rational", m: "যৌক্তিক", s: "Logical" },
    { w: "Rebellion", m: "বিদ্রোহ", s: "Revolt / Uprising" },
    { w: "Recite", m: "আবৃত্তি করা", s: "Repeat aloud" },
    { w: "Reconcile", m: "মিটমাট করা", s: "Settle / Resolve" },
    { w: "Reliable", m: "নির্ভরযোগ্য", s: "Trustworthy" },
    { w: "Reluctant", m: "অনিচ্ছুক", s: "Unwilling" },
    { w: "Remarkable", m: "উল্লেখযোগ্য", s: "Notable / Amazing" },
    { w: "Remedy", m: "প্রতিকার", s: "Cure / Solution" },
    { w: "Remote", m: "প্রত্যন্ত", s: "Distant / Far" },
    { w: "Repent", m: "অনুশোচনা করা", s: "Regret" },
    { w: "Resilient", m: "স্থিতিস্থাপক", s: "Strong / Tough" },
    { w: "Reveal", m: "প্রকাশ করা", s: "Disclose / Show" },
    { w: "Revive", m: "পুনর্জীবিত করা", s: "Restore" },
    { w: "Rigid", m: "কঠোর", s: "Stiff / Inflexible" },
    { w: "Rumor", m: "গুজব", s: "Gossip / Hearsay" },
    { w: "Rural", m: "গ্রামীণ", s: "Rustic / Countryside" },
    { w: "Sacrifice", m: "ত্যাগ", s: "Offering" },
    { w: "Sanitary", m: "স্বাস্থ্যসম্মত", s: "Hygienic / Clean" },
    { w: "Scarcity", m: "স্বল্পতা", s: "Shortage / Dearth" },
    { w: "Skeptical", m: "সন্দেহপ্রবণ", s: "Doubtful" },
    { w: "Solitary", m: "নির্জন", s: "Lonely / Alone" },
    { w: "Sophisticated", m: "অত্যাধুনিক", s: "Advanced / Complex" },
    { w: "Spectacular", m: "দর্শনীয়", s: "Amazing / Stunning" },
    { w: "Spontaneous", m: "স্বতঃস্ফূর্ত", s: "Natural / Unplanned" },
    { w: "Starvation", m: "অনাহার", s: "Hunger / Famine" },
    { w: "Stereotype", m: "গৎবাঁধা ধারণা", s: "Cliché" },
    { w: "Stimulate", m: "উদ্দীপিত করা", s: "Encourage / Arouse" },
    { w: "Stubborn", m: "জেদী", s: "Obstinate" },
    { w: "Substantial", m: "যথেষ্ট", s: "Significant / Large" },
    { w: "Superstition", m: "কুসংস্কার", s: "False belief" },
    { w: "Suppress", m: "দমন করা", s: "Repress / Crush" },
    { w: "Sustainable", m: "টেকসই", s: "Viable / Maintainable" },
    { w: "Tedious", m: "ক্লান্তিকর", s: "Boring / Dull" },
    { w: "Temperament", m: "মেজাজ", s: "Nature / Disposition" },
    { w: "Temporary", m: "অস্থায়ী", s: "Short-term" },
    { w: "Tendency", m: "প্রবণতা", s: "Inclination" },
    { w: "Tolerate", m: "সহ্য করা", s: "Endure / Bear" },
    { w: "Toxic", m: "বিষাক্ত", s: "Poisonous" },
    { w: "Tradition", m: "ঐতিহ্য", s: "Custom / Culture" },
    { w: "Tragedy", m: "বিয়োগান্ত ঘটনা", s: "Disaster / Sadness" },
    { w: "Transform", m: "রূপান্তর করা", s: "Change / Convert" },
    { w: "Transparent", m: "স্বচ্ছ", s: "Clear / See-through" },
    { w: "Trivial", m: "তুচ্ছ", s: "Unimportant / Minor" },
    { w: "Turbulence", m: "অস্থিরতা", s: "Instability / Chaos" },
    { w: "Typical", m: "সাধারণ", s: "Normal / Standard" },
    { w: "Ultimate", m: "চূড়ান্ত", s: "Final / Supreme" },
    { w: "Unanimous", m: "সর্বসম্মত", s: "Agreed by all" },
    { w: "Unique", m: "অনন্য", s: "Distinctive" },
    { w: "Universal", m: "সার্বজনীন", s: "General / Global" },
    { w: "Urban", m: "শহুরে", s: "City / Metropolitan" },
    { w: "Urgent", m: "জরুরি", s: "Pressing / Important" },
    { w: "Vacant", m: "খালি", s: "Empty / Unoccupied" },
    { w: "Vague", m: "অস্পষ্ট", s: "Unclear / Indefinite" },
    { w: "Valid", m: "বৈধ", s: "Legitimate / Logical" },
    { w: "Vanity", m: "অহংকার", s: "Pride / Arrogance" },
    { w: "Variety", m: "বৈচিত্র্য", s: "Diversity" },
    { w: "Vast", m: "বিশাল", s: "Huge / Enormous" },
    { w: "Versatile", m: "বহুমুখী", s: "Flexible / Adaptable" },
    { w: "Victory", m: "বিজয়", s: "Triumph / Win" },
    { w: "Violence", m: "সহিংসতা", s: "Aggression / Brutality" },
    { w: "Virtue", m: "গুণ", s: "Goodness / Merit" },
    { w: "Visible", m: "দৃশ্যমান", s: "Clear / Perceptible" },
    { w: "Visionary", m: "দূরদর্শী", s: "Imaginative / Foresighted" },
    { w: "Vital", m: "অত্যাবশ্যক", s: "Essential / Crucial" },
    { w: "Vivid", m: "প্রাণবন্ত", s: "Bright / Clear" },
    { w: "Voluntary", m: "স্বেচ্ছাসেবী", s: "Optional / Willing" },
    { w: "Vulnerable", m: "অরক্ষিত", s: "Weak / Exposed" },
    { w: "Wander", m: "ঘুরে বেড়ানো", s: "Roam / Stroll" },
    { w: "Welfare", m: "কল্যাণ", s: "Well-being" },
    { w: "Wholesome", m: "স্বাস্থ্যকর", s: "Healthy / Good" },
    { w: "Wicked", m: "দুষ্ট", s: "Evil / Bad" },
    { w: "Wisdom", m: "প্রজ্ঞা", s: "Knowledge / Insight" },
    { w: "Withdraw", m: "প্রত্যাহার করা", s: "Remove / Retreat" },
    { w: "Witness", m: "সাক্ষী", s: "Observer / Spectator" },
    { w: "Worthy", m: "যোগ্য", s: "Deserving / Capable" },
    { w: "Wretched", m: "দুর্ভাগা", s: "Miserable / Unhappy" },
    { w: "Xenophobia", m: "বিদেশী ভীতি", s: "Fear of strangers" },
    { w: "Yearn", m: "আকাঙ্ক্ষা করা", s: "Long / Desire" },
    { w: "Zeal", m: "প্রবল উৎসাহ", s: "Passion / Enthusiasm" },
    { w: "Zenith", m: "শীর্ষবিন্দু", s: "Peak / Pinnacle" },
    { w: "Zest", m: "রুচি/উৎসাহ", s: "Enthusiasm / Flavor" }
];
