/* writing-db.js - Database for Part C (Writing Vault) */

const writingData = {
    stories: {
        title: "Completing Stories",
        rules: [
            "Always give a suitable TITLE at the top of the story.",
            "Do NOT just write the ending. Write the whole story from the beginning.",
            "Keep the story in the Past Tense (unless there is dialogue).",
            "A Moral at the end is optional, but it impresses the examiner.",
            "Make sure the story has a logical flow and paragraph breaks."
        ],
        items: [
            {
                title: "Sheikh Saadi and His Dress",
                moral: "Dress does not make a man great.",
                content: "Sheikh Saadi was a great Persian poet. He was very simple in his ways of life. Once he was invited by the Emperor of Iran to his court. He started his journey for the Emperor's palace. On the way, he took shelter in a rich man's house for a night.\n\nAt that time, Saadi was wearing a very ordinary, cheap dress. The rich man and his servants did not show him much respect or hospitality. They served him very ordinary food. Saadi did not mind and left the place the next morning.\n\nAfter a few days, Saadi was returning from the Emperor's court. This time, the Emperor had given him a rich, gorgeous dress. He again visited the same rich man's house. Seeing his royal dress, the rich man thought he was a noble man. He welcomed Saadi warmly and offered him rich and delicious food.\n\nWhen they sat to eat, Saadi did not eat the food. Instead, he started putting the food into the pockets of his rich dress. The rich man was highly surprised and asked him why he was doing so. Saadi replied, 'A few days ago when I came in an ordinary dress, you served me ordinary food. Today, seeing my rich dress, you have served this delicious food. So, this food is not for me, it is for my dress.' The rich man felt ashamed and apologized for his behavior."
            },
            {
                title: "A Thirsty Crow",
                moral: "Where there is a will, there is a way.",
                content: "It was a hot summer day. A crow became very thirsty. It flew hither and thither in search of water but found none. It became very weak and almost lost all hope of finding water.\n\nSuddenly, it saw a pitcher at a short distance. The crow flew down to it with great hope. But alas! There was very little water at the bottom of the pitcher. The crow tried to drink the water, but its beak could not reach it. It tried to overturn the pitcher, but it was too heavy.\n\nThe crow was disappointed but did not give up. It looked around and saw some pebbles lying nearby. A clever idea came to its mind. It picked up the pebbles one by one in its beak and dropped them into the pitcher.\n\nGradually, the water level rose up to the brim. The crow then drank the water to its heart's content, quenched its thirst, and flew away happily."
            },
            {
                title: "The Lion and the Mouse",
                moral: "Even the smallest friend can be helpful.",
                content: "Once a lion was sleeping peacefully in a forest. Suddenly, a little mouse came out of its hole and started jumping over the lion's body just for fun. The lion woke up and became very angry. He caught the mouse in his huge paw and was about to kill it.\n\nThe mouse was terribly frightened. It begged for its life and said, 'Oh, King of the forest! Please forgive me this time. Let me go. Someday I may be of help to you.' The lion laughed at the idea that a tiny mouse could ever help him, but he took pity on it and let it go.\n\nA few days later, the lion fell into a trap laid by a hunter. He tried his best to break the net but failed. He started roaring loudly in anger and despair. The mouse heard the roar and immediately ran to the spot.\n\nSeeing the lion in danger, the mouse said, 'Don't worry, my lord. I will help you.' The mouse started biting the ropes of the net with its sharp teeth. Soon, it cut the net and freed the lion. The lion thanked the little mouse, and from that day, they became good friends."
            },
            {
                title: "An Honest Woodcutter",
                moral: "Honesty is the best policy.",
                content: "Once there lived a poor but honest woodcutter in a village. He used to cut wood in the forest and sell it in the market to maintain his family. One day, he was cutting wood near a river. Suddenly, his iron axe slipped from his hand and fell into the deep water.\n\nThe woodcutter did not know how to swim. He sat by the river and started weeping bitterly. Hearing his crying, the water goddess Mercury appeared before him. She asked him why he was crying. The woodcutter told her everything.\n\nThe goddess took pity on him. She dived into the water and brought a golden axe. She asked, 'Is this your axe?' The woodcutter said, 'No, this is not mine.' She dived again and brought a silver axe. The woodcutter again said, 'No, it is not mine.'\n\nFinally, she brought the iron axe. The woodcutter became very happy and said, 'Yes, this is my axe.' The goddess was highly pleased with his honesty. She gave him the iron axe and also gave the golden and silver axes as a reward for his honesty."
            },
            {
                title: "The Ant and the Dove",
                moral: "A friend in need is a friend indeed.",
                content: "Once an ant was very thirsty. It went to a river bank to drink water. While drinking, a strong wave suddenly washed it away into the deep water. The ant was about to drown and struggled for its life.\n\nA dove was sitting on a branch of a tree beside the river. It saw the ant in danger and felt pity for it. The dove quickly plucked a broad leaf from the tree and dropped it into the water near the ant. The ant climbed onto the leaf and floated safely to the bank. Thus, its life was saved.\n\nA few days later, the ant was searching for food under the same tree. It saw a hunter aiming his arrow at the dove. The dove did not notice the hunter. The ant realized its friend was in danger and immediately bit the hunter hard on his foot.\n\nThe hunter screamed in pain and missed his aim. Hearing the noise, the dove flew away to safety. The ant was happy that it could save the life of the dove who had saved its life."
            }
        ]
    }, 
    
{
                title: "Who Will Bell the Cat?",
                moral: "It is easy to say but difficult to do.",
                content: "Once upon a time, a large number of mice lived in an old house. They were living happily and moving freely all over the house. But one day, the owner of the house brought a big cat to kill the mice.\n\nThe cat started hunting and killing the mice every day. The mice became very afraid. They could not move freely anymore. They realized that if this continued, soon all of them would be dead. So, they held a secret meeting to find a solution.\n\nMany mice gave many proposals, but none was practical. Finally, a young mouse stood up and said, 'I have a brilliant idea. If we tie a bell around the cat's neck, we will hear it ringing when she approaches us. Then we can easily run and hide in our holes.'\n\nAll the mice clapped and cheered at this brilliant idea. They thought they were finally safe. But suddenly, an old, wise mouse stood up and asked, 'The plan is undoubtedly very good. But I have one simple question. Who will bell the cat?' Hearing this, all the mice became silent. No one had the courage to go near the cat. Thus, the meeting ended in disappointment."
            },
            {
                title: "Bayazid Bostami's Devotion to His Mother",
                moral: "Devotion to mother brings Allah's blessings.",
                content: "Hazrat Bayazid Bostami was a great saint of Islam. Even when he was a young boy, he was deeply devoted to his mother. He served her with great love and care.\n\nOne night, Bayazid was busy studying by the side of his mother's bed. His mother was sleeping. Suddenly, she woke up and asked for a glass of water. Bayazid immediately went to the pitcher to bring water, but to his dismay, there was no water in it.\n\nThe night was very dark, and the nearest fountain was far away from their house. But Bayazid did not hesitate. He took the pitcher and went to the fountain in the dark of night. He filled the pitcher and hurried back home.\n\nWhen he returned, he saw that his mother had fallen asleep again. He did not want to wake her up, nor did he want to keep her waiting if she woke up again. So, he stood quietly beside her bed with the glass of water in his hand.\n\nHours passed, and the sun rose in the east. His mother woke up and was surprised to see Bayazid standing with the glass of water. She realized that her son had been standing all night just for her. Her eyes filled with tears of joy. She prayed to Allah from the bottom of her heart for her son. Allah accepted her prayer, and Bayazid became one of the greatest saints in the world."
            },
            {
                title: "A Liar Shepherd",
                moral: "Nobody believes a liar, even when he speaks the truth.",
                content: "Once there lived a shepherd boy in a village. He used to graze a flock of sheep near a forest. The boy was very naughty and had a bad habit of telling lies and making fun of others.\n\nOne day, while he was grazing his sheep, he thought of a mischievous plan to fool the villagers. He started shouting at the top of his voice, 'Wolf! Wolf! Help! Help!' Hearing his cry, the villagers left their work and rushed to the field with sticks to save the boy and his sheep.\n\nBut when they reached the spot, they found no wolf. The boy started laughing at them and said he was just joking. The villagers became very angry and went back to their work. He repeated the same trick a few days later, and the villagers were fooled again.\n\nHowever, one terrible day, a hungry wolf actually came out of the forest and attacked the sheep. The boy was terrified. He shouted frantically, 'Wolf! Wolf! Please help me!' The villagers heard his cries, but this time, nobody came. They thought the boy was joking again. The wolf killed many of his sheep and then killed the boy as well. The boy paid a heavy price for telling lies."
            },
            {
                title: "The Goose That Laid Golden Eggs",
                moral: "Grasp all, lose all.",
                content: "Once upon a time, there lived a poor farmer in a village. He had a wonderful goose. It was no ordinary goose because every morning it laid a golden egg. The farmer used to sell the golden egg in the market.\n\nSlowly, the farmer and his wife became rich. They bought a good house, good clothes, and plenty of food. But the farmer was very greedy. He was not satisfied with just one egg a day. He wanted to become the richest man in the village overnight.\n\nOne day, he shared his evil thought with his wife. He said, 'Our goose lays one golden egg every day. That means her stomach must be full of golden eggs. If we cut her belly, we can get all the eggs at once and become very rich immediately.'\n\nHis wife agreed to this foolish plan. The greedy farmer took a sharp knife and cut the belly of the goose open. But alas! To his utter shock, he found no golden eggs inside. It was just like the stomach of any other ordinary bird. The goose died instantly. The farmer lost both the magical bird and his daily source of income. He cried bitterly, but it was too late."
            },
            {
                title: "Two Friends and a Bear",
                moral: "A friend in need is a friend indeed.",
                content: "Once, two friends were walking through a dense forest. They promised each other that they would remain united in any danger. They were talking happily when suddenly, they saw a large, terrifying bear approaching them.\n\nSeeing the bear, both of them got very frightened. One of the friends knew how to climb a tree. Without thinking about his friend, he quickly ran and climbed up a tall tree to save his own life. The other friend did not know how to climb.\n\nHe was helpless, but he knew that bears do not touch dead bodies. So, he quickly fell flat on the ground and held his breath, pretending to be dead. The bear came near him. It smelt his nose, ears, and face. Thinking him to be dead, the bear left him unharmed and went away into the forest.\n\nAfter the bear had gone far away, the friend from the tree came down. He smiled and asked, 'My friend, what did the bear whisper in your ear?' The other friend, who was deeply hurt by the selfish behavior, replied, 'The bear advised me never to trust a false friend who leaves you in danger.' The selfish friend felt very ashamed and walked away."
            },
            {
                title: "Robert Bruce and the Spider",
                moral: "Failures are but pillars of success. / Try, try and try again.",
                content: "Robert Bruce was the king of Scotland. He was a brave and noble king. His country was invaded by the English king, Edward I. Bruce fought bravely to defend his country but was defeated. He lost his kingdom and had to flee to save his life.\n\nHe took shelter in a remote, lonely cave in a forest. He was deeply disappointed and lost all hope of regaining his throne. He had already fought six battles against the English and was defeated every time. He thought it was useless to try anymore.\n\nOne day, while he was lying in the cave, he saw a small spider trying to reach the ceiling to weave its web. The spider crawled up a thread but slipped and fell. Bruce noticed that the spider did not give up. It tried again and fell again. \n\nThis happened six times. Bruce thought the spider would finally give up. But to his great surprise, the spider made a seventh attempt. This time, it succeeded in reaching the ceiling and completing its web.\n\nBruce was greatly inspired by the little spider. He thought, 'If a tiny spider can succeed after six failures, why should I give up?' He gathered his courage, organized his army once again, and attacked the English forces. This time, he fought with renewed energy and successfully defeated the enemies, regaining his lost kingdom."
            },
            {
                title: "Dividing the Bread (The Monkey and the Cats)",
                moral: "When two fools fight, a third person takes the advantage.",
                content: "Once, two cats stole a piece of bread from a house. They went to a quiet place to divide it between themselves. But they could not agree on how to divide it equally. Each cat wanted the bigger piece. They started quarreling over the bread.\n\nA cunning monkey was sitting on a tree nearby and watching them. He saw a great opportunity to get some food. He came down and said, 'My dear friends, why are you fighting? Let me help you divide the bread equally. I have a pair of scales.' The cats happily agreed.\n\nThe monkey brought his scales and tore the bread into two pieces. He put them on the scales. One piece was heavier than the other. So, he bit off a small portion from the heavier piece and ate it. \n\nNow, the other piece became heavier. He again took a bite from that piece. He continued doing this until both pieces became very small. The cats realized the monkey's trick. They begged, 'Please give us back our bread. We don't want you to divide it anymore.'\n\nThe monkey smirked and said, 'This small piece is the reward for my labor.' Saying this, he popped the remaining bread into his mouth and climbed back up the tree, leaving the foolish cats hungry and disappointed."
            },
            {
                title: "The Fox and the Grapes (Grapes are Sour)",
                moral: "People pretend to dislike what they cannot get.",
                content: "It was a hot summer day. A hungry fox was wandering in search of food. He walked through the forest but could not find anything to eat. He became very tired and thirsty.\n\nSuddenly, he came near a vineyard. He looked up and saw bunches of ripe, juicy grapes hanging from a high vine. The grapes looked so delicious that the fox's mouth started watering. He thought to himself, 'These grapes will be perfect to quench my thirst and satisfy my hunger.'\n\nThe fox stood on his hind legs and reached up, but the grapes were too high. He took a few steps back, ran, and jumped with all his might, but he still missed them. He tried again and again. He jumped from the left, he jumped from the right, but the grapes remained out of his reach.\n\nAfter a long time, the fox became completely exhausted. He realized that it was impossible for him to reach the grapes. To hide his disappointment, he looked at the grapes with disgust and said, 'Those grapes are sour. I wouldn't eat them even if I caught them.' Saying this, he walked away hungry."
            },
            {
                title: "King Midas and His Golden Touch",
                moral: "Greed brings nothing but suffering.",
                content: "King Midas was an extremely rich king. He had a vast kingdom and a lot of wealth, but he was never satisfied. He loved gold more than anything else in the world. He had a beautiful daughter whom he loved very much, but his love for gold was even greater.\n\nOne day, a wise god appeared before him and offered to grant him a wish. Without a second thought, Midas asked, 'Please grant me the power that whatever I touch will turn into gold.' The god smiled and granted his wish.\n\nMidas was overjoyed. He touched his bed, and it turned into solid gold. He touched the chairs, tables, and doors, and everything turned to gold. He felt he was the happiest man on earth.\n\nSoon, he felt hungry and sat down to eat. But as soon as he touched a piece of bread, it turned into solid gold. He touched a glass of water, and it turned into liquid gold. He realized he could not eat or drink anything. \n\nSuddenly, his beloved daughter came running to him. Midas forgot about his magic touch and hugged her. Instantly, the little girl turned into a lifeless golden statue. Midas broke down in tears. He realized that his greed had destroyed his life. He prayed to the god to take back the golden touch and return his daughter, learning a bitter lesson about greed."
            },
            {
                title: "Unity is Strength (The Old Man and His Sons)",
                moral: "Unity is strength. / United we stand, divided we fall.",
                content: "Once there lived an old farmer in a village. He had four sons. The sons were young and strong, but they always quarreled with one another. The old man was very unhappy and worried about their future. He tried to advise them to live in peace, but they never listened to him.\n\nOne day, the old man fell seriously ill. He realized his death was near. He wanted to teach his sons a final lesson about the importance of unity. He called all his sons to his bedside and asked his servant to bring a bundle of sticks.\n\nWhen the bundle was brought, the old man asked his eldest son to break it. The son tried his best, but the bundle was too strong. Then the other three sons tried one by one, but none of them could break the bundle.\n\nThen the old man smiled and untied the bundle. He gave one stick to each of his sons and asked them to break it. This time, they broke the sticks very easily.\n\nThe old man looked at his sons and said, 'My dear sons, do you see? When the sticks were tied together, none of you could break them. But when they were separated, you broke them easily. If you stay united like the bundle, no one can harm you. But if you quarrel and stay divided, your enemies will easily destroy you.' The sons understood the lesson and promised to remain united forever."
            }, 
paragraphs: {
        title: "Top 15 Paragraphs",
        rules: [
            "Never use multiple paragraphs. A paragraph must be ONE single block of text.",
            "Start with a strong Topic Sentence that introduces the main idea.",
            "Use linkers (Firstly, Secondly, Moreover, Therefore) to connect sentences.",
            "Keep the word count between 150-200 words according to HSC standard.",
            "End with a concluding sentence that summarizes the core message."
        ],
        items: [
            {
                title: "1. Traffic Jam",
                content: "Traffic jam is a common daily scenario in the towns and cities of our country. It refers to a long line of vehicles stuck on the road, unable to move forward. The causes of traffic jam are many. The rapid growth of population and the increasing number of vehicles are the main reasons. Furthermore, many of our roads are narrow and unregulated. Reckless driving, illegal parking, and overtaking tendency of drivers also contribute to this problem. During a traffic jam, people suffer terribly. Office-goers, students, and patients in ambulances are the worst victims. They lose their valuable time and energy. To solve this problem, spacious roads must be constructed. One-way traffic should be introduced in busy areas. Traffic rules must be imposed strictly, and unlicensed vehicles should be banned. Public awareness is also essential. If the government and citizens work together, we can get rid of this unbearable curse."
            },
            {
                title: "2. Food Adulteration",
                content: "Food adulteration refers to the act of making food items impure by adding harmful chemicals or mixing lower-quality substances. It is one of the greatest problems in our country at present. Almost all kinds of food, from daily groceries to fruits and vegetables, are being adulterated. Greedy and dishonest businessmen do this to maximize their profit overnight. They mix formalin, carbide, and textile colors in fruits, fishes, and sweets to preserve them for a long time. Consuming these toxic foods causes fatal diseases like cancer, kidney failure, heart diseases, and liver damage. It is a slow poisoning that is destroying our future generation. The government must take immediate and stern actions against these culprits. Mobile courts should be deployed frequently in markets. Furthermore, public awareness must be raised so that people boycott adulterated food. Ensuring safe food is a fundamental right, and it must be strictly maintained."
            },
            {
                title: "3. Climate Change & Global Warming",
                content: "Climate change means the significant and long-lasting change in the earth's climate and weather patterns. Global warming, which is the gradual increase of the earth's temperature, is the primary cause of climate change. The main culprit behind this is the emission of greenhouse gases like carbon dioxide, methane, and CFCs. Deforestation, rapid industrialization, and the burning of fossil fuels are increasing these gases at an alarming rate. As a result, the polar ice caps are melting, and the sea level is rising. Bangladesh is one of the most vulnerable countries to climate change. If the sea level rises further, the lower southern parts of our country will go under water. Natural disasters like cyclones, floods, and droughts are becoming more frequent. To save our planet, we must stop deforestation and plant more trees. We should use renewable energy sources instead of fossil fuels. A combined global effort is urgently needed to tackle this severe threat."
            },
            {
                title: "4. Deforestation and Tree Plantation",
                content: "Deforestation means cutting down trees in large numbers, whereas tree plantation means planting trees to save the environment. Trees are our best friends. They give us oxygen, food, shade, and timber. They also maintain ecological balance and prevent natural disasters. Unfortunately, some greedy people and ignorant villagers are cutting down trees randomly for fuel, furniture, and housing. This reckless deforestation is causing severe damage to our environment. It leads to global warming, droughts, and soil erosion. If this process continues, our country will soon turn into a desert. To survive, we have no alternative but to plant more trees. June and July are the best months for tree plantation. We can plant trees on both sides of the roads, around our houses, and in unused lands. The government and media should run mass campaigns to encourage people. 'Plant trees, save the environment' should be our national motto."
            },
            {
                title: "5. The Padma Bridge",
                content: "The Padma Bridge is the longest and most dream-fulfilling bridge in the history of Bangladesh. It is a multipurpose road-rail bridge across the mighty Padma River. The bridge is 6.15 kilometers long and 18.10 meters wide, featuring a four-lane highway on the upper level and a single-track railway on the lower level. What makes this bridge a symbol of national pride is that it was built entirely with the self-funding of the Bangladesh government. The construction of this bridge was a massive engineering challenge due to the strong currents of the river. The bridge connects the southern 21 districts directly with the capital, Dhaka. It has brought a revolutionary change in communication, trade, and commerce. Farmers can easily send their goods to Dhaka, and the tourism sector in the south is booming. The Padma Bridge is not just a structure of concrete and steel; it is the symbol of our economic capability and national dignity."
            },
            {
                title: "6. Female Education",
                content: "Female education refers to the education of women, which is essential for the overall development of a nation. Women constitute half of our total population. No nation can prosper keeping half of its population in the dark of ignorance. An educated mother can raise an educated and healthy child, as Napoleon Bonaparte correctly said, 'Give me an educated mother, I shall promise you the birth of a civilized, educated nation.' Educated women can contribute to the family income and the national economy. They become conscious of their rights, health, and children's upbringing. Unfortunately, in our society, girls often face discrimination, early marriage, and poverty, which hinder their education. However, the scenario is changing. The government has taken massive steps, including providing free education and stipends for girls up to the higher secondary level. We must change our social outlook and encourage female education to build a progressive and prosperous Bangladesh."
            },
            {
                title: "7. Drug Addiction",
                content: "Drug addiction is the strong, uncontrollable habit of taking harmful drugs. It is a modern curse that has spread its deadly wings globally, including in Bangladesh. Young people, especially teenagers, are falling victim to this destructive habit. Frustration, unemployment, bad company, lack of family care, and curiosity are the main reasons behind drug addiction. Drugs like heroin, yaba, yaba, phensedyl, and marijuana completely destroy the physical and mental health of the addict. Addicts lose their moral values, memory, and working capacity. To manage money for buying drugs, they often commit crimes like theft, robbery, and hijacking, which disrupts social peace. This problem must be addressed with an iron hand. The smuggling and illegal sale of drugs must be stopped by law enforcement agencies. Parents must spend quality time with their children. Rehabilitation centers should be established to bring addicts back to normal life. Massive public awareness is required to eradicate this social cancer."
            },
            {
                title: "8. Diaspora",
                content: "The term 'diaspora' is used to refer to people who have left their homelands and settled in other parts of the world. Throughout history, there have been massive diasporas. The Jewish people, who were forced to leave their lands in ancient times, are one of the most notable diasporas. In the 20th century, the Palestinian diaspora grabbed world attention. In recent times, millions of people from Africa, Syria, and Myanmar have fled their countries due to war, poverty, and political unrest. Even many Bangladeshi people have migrated to countries like the UK, USA, and Middle Eastern nations in search of better living standards or higher education. While diasporas contribute to the economy of their host countries and send remittances back home, they often face identity crises, racism, and a deep sense of nostalgia for their roots. Globalization has made the diaspora phenomenon more prominent than ever before."
            },
            {
                title: "9. Etiquette and Manners",
                content: "Etiquette and manners are the codes of polite behavior in society. 'Etiquette' is a French word that means the rules of correct behavior, while 'manners' refer to the way of behaving with others. Together, they make a person socially acceptable and beloved by all. We learn etiquette and manners primarily from our parents, families, and educational institutions. Saying 'please,' 'thank you,' and 'excuse me' are basic examples of good manners. Respecting elders, speaking softly, and not interrupting others while they speak are essential parts of etiquette. Manners vary from culture to culture, but the core essence of showing respect remains universal. A man of good manners is respected everywhere, whereas a rude person is disliked, no matter how rich or educated they are. Practicing good etiquette costs nothing but buys everything. It smoothens human relationships and brings peace and harmony to society."
            },
            {
                title: "10. Folk Music",
                content: "Folk music consists of songs and music of a community that are uninfluenced by any sophisticated musical rules or standard music styles. Bangladesh has a rich heritage of folk music which includes Palligiti, Bhatiali, Bhawaiya, Jari, Sari, Gambhira, Lalongiti, and Hasan Raja’s songs. These songs are usually composed by rural, unlettered poets and singers. The instruments used in folk music are very simple, such as the Ektara, Dotara, Dhol, and Bashi. The themes of folk music reflect the daily lives, joys, sorrows, love, and spirituality of the rural people of Bangladesh. For example, Bhatiali is sung by boatmen, while Bhawaiya is popular among cart drivers in the northern region. Folk music touches the heart deeply because of its natural, emotional, and mystic qualities. It connects us to our roots and cultural identity. Though modern band music is dominating today, traditional folk music still holds a permanent place in the hearts of the Bengali people."
            },
            {
                title: "11. Smart Bangladesh",
                content: "Smart Bangladesh is the new visionary goal of the government, aimed at transforming the country into a technologically advanced, prosperous, and sustainable nation by 2041. It is the upgraded version of 'Digital Bangladesh.' The vision of Smart Bangladesh rests on four core pillars: Smart Citizens, Smart Economy, Smart Government, and Smart Society. Smart Citizens will be digitally skilled and innovative. The Smart Economy will be paperless, cashless, and driven by artificial intelligence, e-commerce, and freelancing. Smart Government will ensure transparency, zero corruption, and hassle-free quick services through digitized systems. Finally, a Smart Society will guarantee equality, security, and an improved standard of living for all. To achieve this, the education system must be revolutionized to focus on coding, AI, and practical skills. Uninterrupted high-speed internet must be available everywhere. If properly implemented, Smart Bangladesh will elevate the country to the status of a developed, first-world nation."
            },
            {
                title: "12. Price Hike",
                content: "Price hike means the unusual and sudden increase in the prices of daily essential commodities. It is a burning issue and a terrible curse for the middle and lower-class people of Bangladesh. The causes of price hike are multifaceted. Shortage of supply, hoarding by dishonest syndicates, inflation, and high transport costs are the main reasons. Sometimes, unscrupulous businessmen create artificial crises to make a quick profit. Due to the price hike, low-income people suffer the most. They find it extremely difficult to manage two square meals a day and maintain their families. Their purchasing power remains the same, but the cost of living skyrockets. To control the price hike, the government must take strict measures. Dishonest hoarders and syndicates must be identified and punished severely. Regular market monitoring by mobile courts is essential. The government should also ensure the fair distribution of goods and provide subsidies to the poor to ease their sufferings."
            },
            {
                title: "13. Environmental Pollution",
                content: "Environmental pollution occurs when harmful elements contaminate the environment and disrupt the natural balance. In our country, the environment is being polluted in many ways, primarily through air, water, and sound pollution. Air is polluted by toxic black smoke emitted from unfit vehicles, brickfields, and industries. Water is polluted when chemical fertilizers, industrial waste, and raw sewage are dumped into rivers and canals. Sound pollution is caused by the hydraulic horns of vehicles, loudspeakers, and construction work. Deforestation is also a major factor that accelerates environmental pollution. As a result of this pollution, people are suffering from fatal diseases like asthma, cholera, deafness, and cancer. It is also causing global warming, threatening the existence of all living beings. We must act immediately to stop this destruction. We need to plant more trees, manage waste properly, and use eco-friendly technologies. Creating public awareness is the most crucial step to ensure a safe environment for our future generations."
            },
            {
                title: "14. A Book Fair",
                content: "A book fair is a large-scale exhibition where different types of books are displayed and sold. It is a highly awaited event for book lovers, writers, and publishers. In Bangladesh, the 'Ekushey Boi Mela,' held in February at the Bangla Academy premises, is the largest and most prominent book fair. The fairground is decorated beautifully with hundreds of stalls. Books on literature, science, history, religion, and children's fiction are available there. A book fair becomes a lively gathering place for people of all ages, especially students and intellectuals. Writers often visit the fair, and readers get the thrilling opportunity to collect autographs from their favorite authors. Seminars and cultural programs are also organized there. A book fair plays a vital role in society by spreading knowledge, encouraging the reading habit, and promoting local literature. It reminds us that books are our best friends and the true source of enlightenment."
            },
            {
                title: "15. Uses and Abuses of Mobile Phone",
                content: "The mobile phone is one of the most wonderful inventions of modern science. It is a wireless device that allows us to communicate with anyone across the globe instantly. It has made our daily lives incredibly easy and fast. We can use it for internet browsing, online classes, banking, paying bills, taking photos, and entertainment. In emergencies, it acts as a lifesaver. However, despite its numerous benefits, the mobile phone has some severe dark sides. Excessive use of mobile phones is causing physical and mental health issues, such as poor eyesight, headaches, and insomnia. Many students are getting addicted to mobile gaming and social media, which is ruining their studies and social skills. Furthermore, cybercrimes, blackmailing, and the spread of rumors have increased due to the misuse of smartphones. Therefore, we should be conscious and judicious. We must utilize the positive aspects of the mobile phone and strictly avoid its abuses."
            }
        ]
    },

    letters: {
        title: "Emails & Formal Letters",
        rules: [
            "For EMAILS: Always include 'To:', 'Subject:', and a proper Salutation.",
            "Keep the Email body concise, clear, and to the point.",
            "For FORMAL LETTERS: Include Date, Designation (e.g., The Principal), College Name, and Subject.",
            "Use formal language for applications. Avoid contractions like 'can't' or 'won't'.",
            "Sign off properly (e.g., 'Yours sincerely', or 'Yours obediently')."
        ],
        items: [
            {
                title: "1. Email: Preparation for the HSC Exam",
                content: "To: rafi@email.com\nSubject: My preparation for the upcoming HSC examination.\n\nDear Rafi,\nTake my cordial love. I received your email yesterday. You wanted to know about my preparation for the upcoming HSC examination. \n\nMy preparation is going very well. I have already completed the syllabus for all my subjects. Now, I am purely focusing on revision. I was a bit weak in English and Physics, but with the help of my teachers, I have overcome those difficulties. I am solving previous years' board questions and giving model tests at home to manage my time better. I study for about 10-12 hours a day. \n\nPlease pray for me so that I can achieve a brilliant result. Let me know about your preparation too. Give my regards to your parents.\n\nYours lovingly,\nAsif"
            },
            {
                title: "2. Email: Advising younger brother to study attentively",
                content: "To: sahil@email.com\nSubject: Advice to be sincere in your studies.\n\nDear Sahil,\nI hope you are well. Father called me yesterday and informed me about your recent test results. I am deeply disappointed to see that you have failed in two subjects and scored poorly in the others.\n\nI heard you are spending too much time playing games on your smartphone and associating with bad company. This is the most crucial time of your student life. If you waste your time now, you will suffer heavily in the future. Please realize that time once lost can never be regained. Stop wasting your time, abandon bad company, and concentrate fully on your studies. \n\nI expect a much better result from you in the final exams. Take care of your health.\n\nYour loving brother,\nAsif"
            },
            {
                title: "3. Email: Consoling a friend on his father's death",
                content: "To: taufiq@email.com\nSubject: Condolence on your father's sudden death.\n\nDear Taufiq,\nI am deeply shocked and profoundly saddened to hear the news of your father's sudden demise. I could hardly believe my ears. \n\nI know how terrible this loss is for you and your family. Your father was a very kind, honest, and pious man. He always treated me like his own son. The gap his death has created can never be filled. But remember, death is inevitable, and we must all submit to the will of Almighty Allah. \n\nPlease be strong during this difficult time. You have to take care of your mother and younger sister now. I pray to the Almighty to grant his departed soul Jannat and give you the strength to bear this immense loss.\n\nI will come to visit you as soon as I can.\n\nYours sincerely,\nAsif"
            },
            {
                title: "4. Email: Thanking for a birthday gift",
                content: "To: uncle.jamal@email.com\nSubject: Thank you so much for the wonderful birthday gift.\n\nDear Uncle,\nTake my respectful greetings. I hope you are doing well. We really missed you at my birthday party last night.\n\nHowever, I received the parcel you sent me. When I opened it, I was absolutely thrilled. Thank you so much for the beautiful wristwatch! It is exactly what I needed. I am often late for my classes, and this watch will help me to be punctual. All my friends also praised the elegant design of the watch. This is the best gift I received this year. I will preserve it carefully as a token of your love.\n\nPlease convey my best regards to Aunt and love to the little ones. \n\nYours affectionately,\nAsif"
            },
            {
                title: "5. Email: Congratulating on brilliant success",
                content: "To: fahim@email.com\nSubject: Heartiest congratulations on your brilliant success.\n\nDear Fahim,\nTake my warmest love. I was incredibly overjoyed to see your HSC result published on the internet today. \n\nHeartiest congratulations to you for achieving a GPA 5.00! I always knew that your hard work, dedication, and perseverance would bring such a glorious result. You have made all of us, especially your parents, very proud. Your success proves that genuine effort never goes unrewarded. Now, you must prepare yourself for the university admission tests with the same determination. \n\nI wish you all the best for your future endeavors. Let’s meet this weekend to celebrate your success.\n\nYours truly,\nAsif"
            },
            {
                title: "6. Formal Letter: Permission to go on a study tour",
                content: "Date: 19 February 2026\nTo\nThe Principal,\nDhaka City College, Dhaka.\n\nSubject: Application for permission to go on a study tour.\n\nSir,\nWe, the students of Class XII of your college, beg most respectfully to state that we want to go on a study tour to Mainamati, Rajshahi, next week. It is a place of great historical interest. \n\nA study tour is an essential part of education. It breaks the monotony of continuous classes and broadens our practical knowledge. Two of our senior teachers have kindly agreed to guide us on this tour. We have already collected the necessary funds from our classmates to cover the expenses.\n\nWe, therefore, pray and hope that you would be kind enough to grant us permission to go on the study tour and oblige thereby.\n\nYours obediently,\nAsif Wazed\nOn behalf of the students of Class XII."
            },
            {
                title: "7. Formal Letter: Setting up a Computer Club",
                content: "Date: 19 February 2026\nTo\nThe Principal,\nSylhet Govt. College, Sylhet.\n\nSubject: Application for setting up a computer club in the college.\n\nSir,\nWith due respect, we, the students of your college, would like to state that our college is one of the best institutions in the district. However, we are severely lacking a computer club.\n\nIn this modern era of information technology, computer knowledge is a must for survival and success. Many of us want to learn coding, graphic design, and basic computer skills, but we do not have a dedicated platform. A computer club would provide us with the opportunity to arrange training sessions, workshops, and skill development programs outside class hours.\n\nWe, therefore, request you to take the necessary steps to establish a computer club in our college premises and oblige thereby.\n\nYours obediently,\nAsif Wazed\nOn behalf of the students."
            },
            {
                title: "8. Formal Letter: Relief for flood-affected people",
                content: "Date: 19 February 2026\nTo\nThe Deputy Commissioner,\nSunamganj District, Sylhet.\n\nSubject: Application for relief and medical aid for flood-affected people.\n\nSir,\nI, on behalf of the inhabitants of Tahirpur upazila, beg to draw your kind attention to the miserable condition of the flood-hit people in our locality. \n\nThe recent devastating flood has washed away our crops, domestic animals, and countless houses. Thousands of people have become homeless and are living under the open sky. They are suffering immensely from a lack of food, pure drinking water, and dry clothes. Worse still, waterborne diseases like cholera and diarrhea have broken out in an epidemic form.\n\nI, therefore, fervently pray and hope that you would be kind enough to send sufficient relief materials and medical teams to the affected areas immediately to save human lives.\n\nYours faithfully,\nAsif Wazed\nOn behalf of the people of Tahirpur."
            },
            {
                title: "9. Email: Importance of Reading Newspaper",
                content: "To: sojib@email.com\nSubject: The importance of reading newspapers daily.\n\nDear Sojib,\nI hope you are fine. Yesterday I received a letter from your mother, and she mentioned that you are totally disconnected from world news and never read newspapers.\n\nReading the newspaper is an indispensable habit for a student. It is the mirror of the current world. Mere bookish knowledge is not enough in this competitive era. A newspaper gives you updates on global politics, economics, sports, and science. It broadens your outlook and greatly improves your vocabulary and language skills. Without reading the newspaper, a man is like a frog in a narrow well. \n\nI strongly advise you to build the habit of reading an English daily newspaper from today. It will help you immensely in your future career.\n\nYours ever,\nAsif"
            },
            {
                title: "10. Email: Co-curricular activities of your college",
                content: "To: imran@email.com\nSubject: Co-curricular activities in our college.\n\nDear Imran,\nTake my love. In your last email, you wanted to know about the co-curricular activities of my college. I am very proud to tell you about them.\n\nOur college places equal importance on studies and co-curricular activities. We have a spacious playground where we play football, cricket, and volleyball regularly. We also have a very active debating club and an English language club that arrange weekly sessions. Furthermore, our college publishes an annual magazine where students can publish their poems and articles. We also have a Rover Scout unit and a cultural society that organizes beautiful programs on national holidays. \n\nThese activities keep our minds fresh and help us develop leadership skills. Let me know about your college too.\n\nYours lovingly,\nAsif"
            },
            {
                title: "11. Email: Describing the Prize-Giving Ceremony",
                content: "To: nabil@email.com\nSubject: Description of the annual prize-giving ceremony.\n\nDear Nabil,\nI hope you are doing well. I am writing to share the excitement of our college's annual prize-giving ceremony, which was held yesterday.\n\nThe college campus was decorated beautifully with colorful flags and banners. The local Member of Parliament was the Chief Guest. The program started at 10 AM with the recitation from the Holy Quran. After that, our Principal read out the annual report. Then, the Chief Guest delivered a highly motivating speech and distributed the prizes among the winners. \n\nI am thrilled to inform you that I won two prizes—one for the highest marks in English and another for the debate competition! The event concluded with a brilliant cultural show performed by the students. It was a memorable day.\n\nTake care of yourself.\n\nBest wishes,\nAsif"
            },
            {
                title: "12. Formal Letter: Seat in the college hostel",
                content: "Date: 19 February 2026\nTo\nThe Principal,\nSylhet Board College, Sylhet.\n\nSubject: Application for a seat in the college hostel.\n\nSir,\nWith due respect, I beg to state that I am a regular student of Class XII (Science Group) in your renowned college. My father is a government employee, and recently he has been transferred from Sylhet to Dhaka.\n\nMy family has already shifted to Dhaka. Since I have no close relatives in Sylhet, I have been facing severe accommodation problems. It has become impossible for me to continue my studies smoothly while living in a costly and insecure private mess. I badly need a seat in the college hostel to focus on my upcoming HSC exams.\n\nI, therefore, pray and hope that you would be kind enough to allot me a seat in the college hostel as early as possible and oblige thereby.\n\nYours obediently,\nAsif Wazed\nClass XII, Roll: 12"
            },
            {
                title: "13. Email: Sympathy for hospital admission",
                content: "To: rony@email.com\nSubject: Wishing you a speedy recovery.\n\nDear Rony,\nI was deeply shocked to hear from your brother that you have been admitted to the hospital due to a severe attack of dengue fever.\n\nI know how painful and exhausting this fever can be, but please don't lose heart. The doctors at the hospital are very skilled, and with proper rest and medication, you will be back to normal very soon. Drink plenty of fluids and follow the doctor's advice strictly. Do not worry about the missed classes; I am taking notes for you and will help you cover the syllabus once you return.\n\nI plan to visit you at the hospital tomorrow evening. May Allah grant you a quick and full recovery.\n\nYours ever,\nAsif"
            },
            {
                title: "14. Email: Describing a recent picnic",
                content: "To: sakib@email.com\nSubject: Experience of our recent class picnic.\n\nDear Sakib,\nI hope everything is going well. I am writing to tell you about the wonderful picnic we had last Friday.\n\nOur class went to the Jaflong wetland in Sylhet. We reached there by bus at 9 AM. The natural beauty of the place, with its crystal-clear water and distant hills, left us mesmerized. We walked around, took hundreds of photographs, and even sang songs in a boat. The most exciting part was the cooking; we all helped our teachers cook Biryani, which tasted exceptionally delicious in that open environment. We played games and had a raffle draw before returning home at sunset.\n\nWe really missed your presence. If you were there, our joy would have been doubled. \n\nBest regards,\nAsif"
            },
            {
                title: "15. Formal Letter: Testimonial",
                content: "Date: 19 February 2026\nTo\nThe Principal,\nGovernment Model College, Sylhet.\n\nSubject: Application for a testimonial.\n\nSir,\nWith due respect, I beg to state that I was a student of the Science group in your college. I passed the HSC examination from your institution in 2025 and secured a GPA of 5.00.\n\nNow, I wish to apply for admission to a university. For this purpose, I require a character certificate or a testimonial from you, stating my academic achievements and behavior during my time at the college. During my college life, I actively participated in the college debating club and had no record of disciplinary issues.\n\nI, therefore, pray and hope that you would be kind enough to issue me a testimonial at your earliest convenience and oblige thereby.\n\nYours obediently,\nAsif Wazed\nHSC Roll: 102345\nPassing Year: 2025"
            }
        ]
    }
