/* writing-db.js - Database for Part C (Writing Vault) */

const writingData = {
    stories: {
        title: "Completing Stories",
        rules: [
            "Always give a suitable TITLE at the top of the story.",
            "Do NOT just write the ending. Write the whole story from the beginning.",
            "Keep the story in the Past Tense (unless there is dialogue).",
            "A Moral at the end is optional, but it impresses the examiner.",
            "Make sure the story has a logical flow and paragraph breaks."
        ],
        items: [
            {
                title: "Sheikh Saadi and His Dress",
                moral: "Dress does not make a man great.",
                content: "Sheikh Saadi was a great Persian poet. He was very simple in his ways of life. Once he was invited by the Emperor of Iran to his court. He started his journey for the Emperor's palace. On the way, he took shelter in a rich man's house for a night.\n\nAt that time, Saadi was wearing a very ordinary, cheap dress. The rich man and his servants did not show him much respect or hospitality. They served him very ordinary food. Saadi did not mind and left the place the next morning.\n\nAfter a few days, Saadi was returning from the Emperor's court. This time, the Emperor had given him a rich, gorgeous dress. He again visited the same rich man's house. Seeing his royal dress, the rich man thought he was a noble man. He welcomed Saadi warmly and offered him rich and delicious food.\n\nWhen they sat to eat, Saadi did not eat the food. Instead, he started putting the food into the pockets of his rich dress. The rich man was highly surprised and asked him why he was doing so. Saadi replied, 'A few days ago when I came in an ordinary dress, you served me ordinary food. Today, seeing my rich dress, you have served this delicious food. So, this food is not for me, it is for my dress.' The rich man felt ashamed and apologized for his behavior."
            },
            {
                title: "A Thirsty Crow",
                moral: "Where there is a will, there is a way.",
                content: "It was a hot summer day. A crow became very thirsty. It flew hither and thither in search of water but found none. It became very weak and almost lost all hope of finding water.\n\nSuddenly, it saw a pitcher at a short distance. The crow flew down to it with great hope. But alas! There was very little water at the bottom of the pitcher. The crow tried to drink the water, but its beak could not reach it. It tried to overturn the pitcher, but it was too heavy.\n\nThe crow was disappointed but did not give up. It looked around and saw some pebbles lying nearby. A clever idea came to its mind. It picked up the pebbles one by one in its beak and dropped them into the pitcher.\n\nGradually, the water level rose up to the brim. The crow then drank the water to its heart's content, quenched its thirst, and flew away happily."
            },
            {
                title: "The Lion and the Mouse",
                moral: "Even the smallest friend can be helpful.",
                content: "Once a lion was sleeping peacefully in a forest. Suddenly, a little mouse came out of its hole and started jumping over the lion's body just for fun. The lion woke up and became very angry. He caught the mouse in his huge paw and was about to kill it.\n\nThe mouse was terribly frightened. It begged for its life and said, 'Oh, King of the forest! Please forgive me this time. Let me go. Someday I may be of help to you.' The lion laughed at the idea that a tiny mouse could ever help him, but he took pity on it and let it go.\n\nA few days later, the lion fell into a trap laid by a hunter. He tried his best to break the net but failed. He started roaring loudly in anger and despair. The mouse heard the roar and immediately ran to the spot.\n\nSeeing the lion in danger, the mouse said, 'Don't worry, my lord. I will help you.' The mouse started biting the ropes of the net with its sharp teeth. Soon, it cut the net and freed the lion. The lion thanked the little mouse, and from that day, they became good friends."
            },
            {
                title: "An Honest Woodcutter",
                moral: "Honesty is the best policy.",
                content: "Once there lived a poor but honest woodcutter in a village. He used to cut wood in the forest and sell it in the market to maintain his family. One day, he was cutting wood near a river. Suddenly, his iron axe slipped from his hand and fell into the deep water.\n\nThe woodcutter did not know how to swim. He sat by the river and started weeping bitterly. Hearing his crying, the water goddess Mercury appeared before him. She asked him why he was crying. The woodcutter told her everything.\n\nThe goddess took pity on him. She dived into the water and brought a golden axe. She asked, 'Is this your axe?' The woodcutter said, 'No, this is not mine.' She dived again and brought a silver axe. The woodcutter again said, 'No, it is not mine.'\n\nFinally, she brought the iron axe. The woodcutter became very happy and said, 'Yes, this is my axe.' The goddess was highly pleased with his honesty. She gave him the iron axe and also gave the golden and silver axes as a reward for his honesty."
            },
            {
                title: "The Ant and the Dove",
                moral: "A friend in need is a friend indeed.",
                content: "Once an ant was very thirsty. It went to a river bank to drink water. While drinking, a strong wave suddenly washed it away into the deep water. The ant was about to drown and struggled for its life.\n\nA dove was sitting on a branch of a tree beside the river. It saw the ant in danger and felt pity for it. The dove quickly plucked a broad leaf from the tree and dropped it into the water near the ant. The ant climbed onto the leaf and floated safely to the bank. Thus, its life was saved.\n\nA few days later, the ant was searching for food under the same tree. It saw a hunter aiming his arrow at the dove. The dove did not notice the hunter. The ant realized its friend was in danger and immediately bit the hunter hard on his foot.\n\nThe hunter screamed in pain and missed his aim. Hearing the noise, the dove flew away to safety. The ant was happy that it could save the life of the dove who had saved its life."
            }
        ]
    }, 
    
{
                title: "Who Will Bell the Cat?",
                moral: "It is easy to say but difficult to do.",
                content: "Once upon a time, a large number of mice lived in an old house. They were living happily and moving freely all over the house. But one day, the owner of the house brought a big cat to kill the mice.\n\nThe cat started hunting and killing the mice every day. The mice became very afraid. They could not move freely anymore. They realized that if this continued, soon all of them would be dead. So, they held a secret meeting to find a solution.\n\nMany mice gave many proposals, but none was practical. Finally, a young mouse stood up and said, 'I have a brilliant idea. If we tie a bell around the cat's neck, we will hear it ringing when she approaches us. Then we can easily run and hide in our holes.'\n\nAll the mice clapped and cheered at this brilliant idea. They thought they were finally safe. But suddenly, an old, wise mouse stood up and asked, 'The plan is undoubtedly very good. But I have one simple question. Who will bell the cat?' Hearing this, all the mice became silent. No one had the courage to go near the cat. Thus, the meeting ended in disappointment."
            },
            {
                title: "Bayazid Bostami's Devotion to His Mother",
                moral: "Devotion to mother brings Allah's blessings.",
                content: "Hazrat Bayazid Bostami was a great saint of Islam. Even when he was a young boy, he was deeply devoted to his mother. He served her with great love and care.\n\nOne night, Bayazid was busy studying by the side of his mother's bed. His mother was sleeping. Suddenly, she woke up and asked for a glass of water. Bayazid immediately went to the pitcher to bring water, but to his dismay, there was no water in it.\n\nThe night was very dark, and the nearest fountain was far away from their house. But Bayazid did not hesitate. He took the pitcher and went to the fountain in the dark of night. He filled the pitcher and hurried back home.\n\nWhen he returned, he saw that his mother had fallen asleep again. He did not want to wake her up, nor did he want to keep her waiting if she woke up again. So, he stood quietly beside her bed with the glass of water in his hand.\n\nHours passed, and the sun rose in the east. His mother woke up and was surprised to see Bayazid standing with the glass of water. She realized that her son had been standing all night just for her. Her eyes filled with tears of joy. She prayed to Allah from the bottom of her heart for her son. Allah accepted her prayer, and Bayazid became one of the greatest saints in the world."
            },
            {
                title: "A Liar Shepherd",
                moral: "Nobody believes a liar, even when he speaks the truth.",
                content: "Once there lived a shepherd boy in a village. He used to graze a flock of sheep near a forest. The boy was very naughty and had a bad habit of telling lies and making fun of others.\n\nOne day, while he was grazing his sheep, he thought of a mischievous plan to fool the villagers. He started shouting at the top of his voice, 'Wolf! Wolf! Help! Help!' Hearing his cry, the villagers left their work and rushed to the field with sticks to save the boy and his sheep.\n\nBut when they reached the spot, they found no wolf. The boy started laughing at them and said he was just joking. The villagers became very angry and went back to their work. He repeated the same trick a few days later, and the villagers were fooled again.\n\nHowever, one terrible day, a hungry wolf actually came out of the forest and attacked the sheep. The boy was terrified. He shouted frantically, 'Wolf! Wolf! Please help me!' The villagers heard his cries, but this time, nobody came. They thought the boy was joking again. The wolf killed many of his sheep and then killed the boy as well. The boy paid a heavy price for telling lies."
            },
            {
                title: "The Goose That Laid Golden Eggs",
                moral: "Grasp all, lose all.",
                content: "Once upon a time, there lived a poor farmer in a village. He had a wonderful goose. It was no ordinary goose because every morning it laid a golden egg. The farmer used to sell the golden egg in the market.\n\nSlowly, the farmer and his wife became rich. They bought a good house, good clothes, and plenty of food. But the farmer was very greedy. He was not satisfied with just one egg a day. He wanted to become the richest man in the village overnight.\n\nOne day, he shared his evil thought with his wife. He said, 'Our goose lays one golden egg every day. That means her stomach must be full of golden eggs. If we cut her belly, we can get all the eggs at once and become very rich immediately.'\n\nHis wife agreed to this foolish plan. The greedy farmer took a sharp knife and cut the belly of the goose open. But alas! To his utter shock, he found no golden eggs inside. It was just like the stomach of any other ordinary bird. The goose died instantly. The farmer lost both the magical bird and his daily source of income. He cried bitterly, but it was too late."
            },
            {
                title: "Two Friends and a Bear",
                moral: "A friend in need is a friend indeed.",
                content: "Once, two friends were walking through a dense forest. They promised each other that they would remain united in any danger. They were talking happily when suddenly, they saw a large, terrifying bear approaching them.\n\nSeeing the bear, both of them got very frightened. One of the friends knew how to climb a tree. Without thinking about his friend, he quickly ran and climbed up a tall tree to save his own life. The other friend did not know how to climb.\n\nHe was helpless, but he knew that bears do not touch dead bodies. So, he quickly fell flat on the ground and held his breath, pretending to be dead. The bear came near him. It smelt his nose, ears, and face. Thinking him to be dead, the bear left him unharmed and went away into the forest.\n\nAfter the bear had gone far away, the friend from the tree came down. He smiled and asked, 'My friend, what did the bear whisper in your ear?' The other friend, who was deeply hurt by the selfish behavior, replied, 'The bear advised me never to trust a false friend who leaves you in danger.' The selfish friend felt very ashamed and walked away."
            },
            {
                title: "Robert Bruce and the Spider",
                moral: "Failures are but pillars of success. / Try, try and try again.",
                content: "Robert Bruce was the king of Scotland. He was a brave and noble king. His country was invaded by the English king, Edward I. Bruce fought bravely to defend his country but was defeated. He lost his kingdom and had to flee to save his life.\n\nHe took shelter in a remote, lonely cave in a forest. He was deeply disappointed and lost all hope of regaining his throne. He had already fought six battles against the English and was defeated every time. He thought it was useless to try anymore.\n\nOne day, while he was lying in the cave, he saw a small spider trying to reach the ceiling to weave its web. The spider crawled up a thread but slipped and fell. Bruce noticed that the spider did not give up. It tried again and fell again. \n\nThis happened six times. Bruce thought the spider would finally give up. But to his great surprise, the spider made a seventh attempt. This time, it succeeded in reaching the ceiling and completing its web.\n\nBruce was greatly inspired by the little spider. He thought, 'If a tiny spider can succeed after six failures, why should I give up?' He gathered his courage, organized his army once again, and attacked the English forces. This time, he fought with renewed energy and successfully defeated the enemies, regaining his lost kingdom."
            },
            {
                title: "Dividing the Bread (The Monkey and the Cats)",
                moral: "When two fools fight, a third person takes the advantage.",
                content: "Once, two cats stole a piece of bread from a house. They went to a quiet place to divide it between themselves. But they could not agree on how to divide it equally. Each cat wanted the bigger piece. They started quarreling over the bread.\n\nA cunning monkey was sitting on a tree nearby and watching them. He saw a great opportunity to get some food. He came down and said, 'My dear friends, why are you fighting? Let me help you divide the bread equally. I have a pair of scales.' The cats happily agreed.\n\nThe monkey brought his scales and tore the bread into two pieces. He put them on the scales. One piece was heavier than the other. So, he bit off a small portion from the heavier piece and ate it. \n\nNow, the other piece became heavier. He again took a bite from that piece. He continued doing this until both pieces became very small. The cats realized the monkey's trick. They begged, 'Please give us back our bread. We don't want you to divide it anymore.'\n\nThe monkey smirked and said, 'This small piece is the reward for my labor.' Saying this, he popped the remaining bread into his mouth and climbed back up the tree, leaving the foolish cats hungry and disappointed."
            },
            {
                title: "The Fox and the Grapes (Grapes are Sour)",
                moral: "People pretend to dislike what they cannot get.",
                content: "It was a hot summer day. A hungry fox was wandering in search of food. He walked through the forest but could not find anything to eat. He became very tired and thirsty.\n\nSuddenly, he came near a vineyard. He looked up and saw bunches of ripe, juicy grapes hanging from a high vine. The grapes looked so delicious that the fox's mouth started watering. He thought to himself, 'These grapes will be perfect to quench my thirst and satisfy my hunger.'\n\nThe fox stood on his hind legs and reached up, but the grapes were too high. He took a few steps back, ran, and jumped with all his might, but he still missed them. He tried again and again. He jumped from the left, he jumped from the right, but the grapes remained out of his reach.\n\nAfter a long time, the fox became completely exhausted. He realized that it was impossible for him to reach the grapes. To hide his disappointment, he looked at the grapes with disgust and said, 'Those grapes are sour. I wouldn't eat them even if I caught them.' Saying this, he walked away hungry."
            },
            {
                title: "King Midas and His Golden Touch",
                moral: "Greed brings nothing but suffering.",
                content: "King Midas was an extremely rich king. He had a vast kingdom and a lot of wealth, but he was never satisfied. He loved gold more than anything else in the world. He had a beautiful daughter whom he loved very much, but his love for gold was even greater.\n\nOne day, a wise god appeared before him and offered to grant him a wish. Without a second thought, Midas asked, 'Please grant me the power that whatever I touch will turn into gold.' The god smiled and granted his wish.\n\nMidas was overjoyed. He touched his bed, and it turned into solid gold. He touched the chairs, tables, and doors, and everything turned to gold. He felt he was the happiest man on earth.\n\nSoon, he felt hungry and sat down to eat. But as soon as he touched a piece of bread, it turned into solid gold. He touched a glass of water, and it turned into liquid gold. He realized he could not eat or drink anything. \n\nSuddenly, his beloved daughter came running to him. Midas forgot about his magic touch and hugged her. Instantly, the little girl turned into a lifeless golden statue. Midas broke down in tears. He realized that his greed had destroyed his life. He prayed to the god to take back the golden touch and return his daughter, learning a bitter lesson about greed."
            },
            {
                title: "Unity is Strength (The Old Man and His Sons)",
                moral: "Unity is strength. / United we stand, divided we fall.",
                content: "Once there lived an old farmer in a village. He had four sons. The sons were young and strong, but they always quarreled with one another. The old man was very unhappy and worried about their future. He tried to advise them to live in peace, but they never listened to him.\n\nOne day, the old man fell seriously ill. He realized his death was near. He wanted to teach his sons a final lesson about the importance of unity. He called all his sons to his bedside and asked his servant to bring a bundle of sticks.\n\nWhen the bundle was brought, the old man asked his eldest son to break it. The son tried his best, but the bundle was too strong. Then the other three sons tried one by one, but none of them could break the bundle.\n\nThen the old man smiled and untied the bundle. He gave one stick to each of his sons and asked them to break it. This time, they broke the sticks very easily.\n\nThe old man looked at his sons and said, 'My dear sons, do you see? When the sticks were tied together, none of you could break them. But when they were separated, you broke them easily. If you stay united like the bundle, no one can harm you. But if you quarrel and stay divided, your enemies will easily destroy you.' The sons understood the lesson and promised to remain united forever."
            }
